// [1.3] 연관 규칙 (Association Rule) + [1.4] 차원 축소 (Dimensionality Reduction)
// List3.md 기준 전체 리프 항목 콘텐츠. algorithms.js와 병합하지 않고 별도 파일로 관리합니다.
const CONTENT_1_3_1_4 = [
  {
    id: 'apriori',
    category: 'unsup',
    subcategory: 'association',
    title: 'Apriori 알고리즘 (선험적 알고리즘)',
    subtitle: '빈발 항목집합을 후보 생성-검사 방식으로 찾아내는 연관규칙 마이닝의 시초 알고리즘',
    overview: `<p>거래 데이터베이스에서 함께 자주 등장하는 항목의 조합(빈발 항목집합)을 찾은 뒤, 이를 바탕으로 "A를 사면 B도 산다" 형태의 연관규칙을 도출합니다. 크기 k인 빈발 항목집합으로부터 크기 k+1의 후보를 생성하고, 데이터베이스를 반복 스캔하며 지지도를 검사하는 candidate generate-and-test 방식을 사용합니다. Agrawal과 Srikant가 1994년에 제안했으며, 연관규칙 마이닝의 표준 출발점으로 여겨집니다.</p>`,
    formula: `X &#8838; Y &#8658; support(X) &#8805; support(Y)  (하향 폐쇄성/Apriori 원리 — 부분집합의 지지도는 항상 상위집합 이상)`,
    features: `<p><strong>장점</strong> — 원리가 단순하고 직관적이며, 하향 폐쇄성(anti-monotone) 원리로 탐색 공간을 효과적으로 가지치기할 수 있습니다.</p><p><strong>단점</strong> — 항목이 많거나 최소 지지도가 낮을수록 후보 항목집합 수가 폭증하고, 데이터베이스를 여러 번 반복 스캔해야 해서 대용량 데이터에서는 느립니다.</p>`,
    applications: `<p>장바구니 분석(마켓 바스켓), 추천 상품 결합 진열, 웹 클릭 로그에서의 동시 방문 페이지 분석 등 전통적 데이터마이닝 실습에 널리 쓰입니다. 파이썬에서는 scikit-learn에는 구현되어 있지 않고, <code>mlxtend.frequent_patterns.apriori</code> 라이브러리가 사실상의 표준 구현으로 사용됩니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'charm',
    category: 'unsup',
    subcategory: 'association',
    title: 'CHARM (Closed Association Rule Mining)',
    subtitle: '중복 없는 폐쇄 빈발 항목집합만을 효율적으로 찾아내는 이중 탐색 알고리즘',
    overview: `<p>Zaki와 Hsiao가 2002년에 제안한 알고리즘으로, 모든 빈발 항목집합 대신 "폐쇄(closed)" 항목집합만을 찾습니다. 항목집합과 그 항목집합이 등장하는 트랜잭션 ID 집합(tidset)을 함께 탐색하는 이중 탐색 트리(itemset-tidset tree)를 이용하며, 같은 tidset을 갖는 접두사 동등 클래스(prefix equivalence class)를 묶어 탐색을 건너뛰는 하이브리드 검색으로 속도를 높입니다.</p>`,
    formula: `itemset X는 폐쇄집합 &#8660; &#8708;Y &#8835; X such that t(Y) = t(X)인 Y가 존재하지 않음 (t(X): X를 포함하는 트랜잭션 ID 집합)`,
    features: `<p><strong>장점</strong> — 폐쇄 항목집합만 열거하므로 전체 빈발 항목집합보다 결과 수가 훨씬 적으면서도 동일한 정보(지지도)를 손실 없이 표현합니다.</p><p><strong>단점</strong> — tidset 교집합 연산과 해시 기반 비폐쇄집합 제거 과정에서 메모리 사용량이 늘어날 수 있고, 매우 희소한 데이터에서는 이점이 줄어듭니다.</p>`,
    applications: `<p>대용량 트랜잭션 데이터에서 중복 규칙 없이 대표 항목집합만 압축해 보고 싶을 때 사용됩니다. scikit-learn이나 mlxtend에는 구현되어 있지 않으며, Philippe Fournier-Viger가 개발한 Java 오픈소스 패턴 마이닝 라이브러리 SPMF에 CHARM 구현이 포함되어 있습니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'declat',
    category: 'unsup',
    subcategory: 'association',
    title: 'dEclat (Diffset Eclat)',
    subtitle: '트랜잭션 ID 집합 대신 차집합(diffset)만 저장해 메모리를 절약하는 Eclat의 개선판',
    overview: `<p>Zaki와 Gouda가 2003년에 제안한 알고리즘으로, Eclat처럼 수직 데이터 형식(item별 tidset)을 사용하되, 각 후보 항목집합의 tidset 전체를 저장하는 대신 그 항목집합을 만든 부모 항목집합과의 차집합(diffset)만 저장합니다. 이를 통해 지지도 계산에 필요한 중간 결과의 메모리 사용량을 크게 줄이고, 더 낮은 최소 지지도에서도 마이닝이 가능해집니다.</p>`,
    formula: `d(P&#8342;) = t(P&#8342;&#8331;&#8321;) &#8726; t(P&#8342;)  (부모 항목집합 tidset과의 차집합만 저장)`,
    features: `<p><strong>장점</strong> — diffset은 일반적으로 tidset보다 훨씬 작아 메모리 효율이 뛰어나고, Eclat보다 낮은 지지도 임계값에서도 동작합니다.</p><p><strong>단점</strong> — 데이터가 매우 조밀(dense)한 경우에는 diffset이 오히려 tidset보다 커질 수 있어 항상 유리한 것은 아닙니다.</p>`,
    applications: `<p>Eclat 계열 알고리즘 중 메모리 제약이 있는 환경에서 대규모 트랜잭션 데이터를 마이닝할 때 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, SPMF 라이브러리에서 dEclat 구현을 제공합니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'eclat',
    category: 'unsup',
    subcategory: 'association',
    title: 'Eclat (Equivalence Class Transformation)',
    subtitle: '수직 데이터 형식과 tidset 교집합만으로 지지도를 계산하는 깊이 우선 빈발 항목집합 마이닝',
    overview: `<p>Zaki 등이 제안한 알고리즘으로, 거래를 "항목 → 트랜잭션 ID 집합(tidset)" 형태의 수직 데이터 구조로 표현합니다. 두 항목집합의 지지도는 각 tidset의 교집합 크기로 바로 계산되므로 Apriori처럼 데이터베이스를 반복 스캔할 필요가 없고, 깊이 우선 탐색으로 빈발 항목집합을 확장해 나갑니다.</p>`,
    formula: `t(X &#8746; Y) = t(X) &#8745; t(Y),  support(X &#8746; Y) = |t(X) &#8745; t(Y)|`,
    features: `<p><strong>장점</strong> — 교집합 연산만으로 지지도를 구할 수 있어 데이터베이스 재스캔이 필요 없고, Apriori보다 대체로 빠릅니다.</p><p><strong>단점</strong> — 항목 수가 많아지면 tidset 자체가 커져 메모리 사용량이 늘어나고, 매우 긴 tidset의 교집합 연산 비용이 커질 수 있습니다.</p>`,
    applications: `<p>Apriori보다 빠른 빈발 항목집합 마이닝이 필요한 중대형 트랜잭션 데이터에 사용됩니다. scikit-learn에는 구현이 없으며, mlxtend에도 Eclat은 포함되어 있지 않아(Apriori/FP-Growth/FP-Max만 제공) SPMF 등 별도 패턴 마이닝 라이브러리를 사용해야 합니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'fp-growth',
    category: 'unsup',
    subcategory: 'association',
    title: 'FP-Growth (Frequent Pattern Growth)',
    subtitle: '후보 항목집합을 생성하지 않고 FP-트리를 재귀적으로 압축·분해해 빈발 패턴을 찾는 알고리즘',
    overview: `<p>Han, Pei, Yin이 2000년에 제안한 알고리즘으로, 데이터베이스를 두 번만 스캔해 전체 트랜잭션을 FP-트리라는 압축된 접두사 트리 구조에 저장합니다. 이후 각 항목에 대한 조건부 패턴 베이스(conditional pattern base)와 조건부 FP-트리를 재귀적으로 만들어가며 후보 생성 없이 빈발 항목집합을 직접 찾아냅니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 후보 항목집합을 생성하지 않아 Apriori보다 훨씬 빠르고, 데이터베이스를 두 번만 스캔하면 됩니다.</p><p><strong>단점</strong> — FP-트리 전체를 메모리에 올려야 하므로 매우 희소하거나 항목 종류가 극히 많은 데이터에서는 트리가 비대해질 수 있습니다.</p>`,
    applications: `<p>실무에서 가장 널리 쓰이는 빈발 패턴 마이닝 알고리즘으로, 장바구니 분석·추천 시스템의 연관 상품 탐색 등에 사용됩니다. scikit-learn에는 없지만 mlxtend에 <code>fpgrowth</code> 함수로 구현되어 있어 실무에서 바로 사용할 수 있습니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'fp-tree-construction',
    category: 'unsup',
    subcategory: 'association',
    title: 'FP-Tree Construction (FP-트리 구성)',
    subtitle: 'FP-Growth의 핵심 자료구조인 FP-트리를 데이터베이스 2회 스캔만으로 만들어내는 절차',
    overview: `<p>FP-Growth 알고리즘의 기반이 되는 압축 자료구조 구축 과정입니다. 1차 스캔으로 각 항목의 지지도를 구해 빈발 항목만 남기고 지지도 내림차순으로 정렬한 뒤, 2차 스캔에서 각 트랜잭션의 빈발 항목들을 이 순서대로 트리에 삽입하며 공통 접두사를 공유하는 경로를 병합합니다. 같은 항목을 가리키는 노드들은 헤더 테이블(header table)의 노드 링크로 서로 연결되어 이후 조건부 패턴 베이스 추출에 사용됩니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 트랜잭션 간 공통 접두사를 공유해 원본 데이터보다 훨씬 압축된 형태로 빈발 정보를 보존합니다.</p><p><strong>단점</strong> — 항목 정렬 순서에 따라 트리의 압축률이 달라지고, 항목 종류가 매우 많으면 트리 크기와 헤더 테이블 관리 비용이 커집니다.</p>`,
    applications: `<p>FP-Growth, FP-Max, H-Mine 등 FP-트리 기반 패턴 마이닝 알고리즘 전반의 전처리 단계로 사용됩니다. 독립적인 scikit-learn/mlxtend API는 없으며, mlxtend의 <code>fpgrowth</code>·<code>fpmax</code> 함수 내부에 이 구성 로직이 포함되어 있습니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'h-mine',
    category: 'unsup',
    subcategory: 'association',
    title: 'H-Mine (Hyper-structure Mining)',
    subtitle: '메모리 사용량이 예측 가능한 하이퍼링크 구조(H-struct)로 빈발 패턴을 마이닝하는 알고리즘',
    overview: `<p>Pei와 Han 등이 2001년 ICDM에서 발표한 알고리즘으로, H-struct라는 하이퍼링크 기반 자료구조를 사용해 마이닝 과정에서 링크를 동적으로 조정합니다. 메모리 기반 환경에서는 매우 정밀하게 예측 가능한 메모리 비용으로 빠르게 동작하며, 데이터가 조밀해지면 조건부 FP-트리를 동적으로 함께 구성해 성능을 보완하는 "space-preserving mining" 방식을 제안했습니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 메모리 사용량이 사전에 예측 가능할 만큼 작고, 희소한 데이터베이스에서 특히 빠릅니다.</p><p><strong>단점</strong> — 데이터가 매우 조밀할 때는 단독으로는 FP-Growth 계열보다 불리할 수 있어 FP-트리 방식과 병행해야 합니다.</p>`,
    applications: `<p>대용량이면서 희소한 트랜잭션 데이터베이스, 데이터베이스 파티셔닝을 통한 확장이 필요한 상황에 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, SPMF 라이브러리가 H-Mine 구현을 제공합니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'lcm',
    category: 'unsup',
    subcategory: 'association',
    title: 'LCM (Linear time Closed itemset Miner)',
    subtitle: '폐쇄 항목집합 개수에 비례하는 선형 시간으로 동작하는 초고속 폐쇄 항목집합 마이너',
    overview: `<p>Uno가 2003~2004년에 제안한 알고리즘으로, 빈발 폐쇄 항목집합들 사이에 부모-자식 관계를 정의해 이들이 하나의 트리 형태 탐색 경로를 이루도록 만듭니다. 이 경로를 따라가면 폐쇄 항목집합의 개수에 선형 비례하는 시간에 전체 폐쇄 항목집합을 열거할 수 있어, 폐쇄/빈발/최대 항목집합 마이닝 대회(FIMI)에서 가장 빠른 알고리즘 중 하나로 꼽혔습니다.</p>`,
    formula: `전체 실행 시간 &#8733; |폐쇄 빈발 항목집합의 개수| &#215; ||D||  (출력 다항 시간, PPC-extension 기반 트리 탐색)`,
    features: `<p><strong>장점</strong> — 폐쇄 항목집합 열거에 있어 이론적으로도 실무적으로도 매우 효율적이며, 최대 항목집합(LCMmax)·빈발 항목집합(LCMfreq) 마이닝으로도 확장됩니다.</p><p><strong>단점</strong> — 구현이 CHARM 등에 비해 복잡하고, 매우 낮은 지지도에서는 여전히 결과 수 자체가 폭증할 수 있습니다.</p>`,
    applications: `<p>대규모 트랜잭션 데이터에서 폐쇄/최대 빈발 항목집합을 신속히 구해야 하는 벤치마크·연구용 데이터마이닝에 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, 저자가 공개한 LCM 구현체와 Java 기반 SPMF, jlcm(멀티스레드 Java) 등에서 제공됩니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'fuzzy-association-rules',
    category: 'unsup',
    subcategory: 'association',
    title: '퍼지 연관규칙 (Fuzzy Association Rules)',
    subtitle: '수치형 속성을 딱딱한 구간 대신 퍼지 소속 함수로 표현해 연관규칙을 마이닝하는 기법',
    overview: `<p>Kuok, Fu, Wong이 1998년 SIGMOD Record에 제안한 개념으로, 나이·소득처럼 연속적인 수치 속성을 "젊음", "중간", "많음" 같은 언어적 용어와 소속 함수(membership function)로 표현합니다. 하드한 구간 분할 대신 0~1 사이의 소속도를 사용하므로, 구간 경계 근처의 값이 여러 범주에 걸쳐 완만하게 반영되어 더 자연스럽고 해석하기 쉬운 규칙을 얻을 수 있습니다.</p>`,
    formula: `fuzzy-support(A) = &#8721;&#8348; min(&#956;&#8321;(t),...,&#956;&#8344;(t)) / N  (각 트랜잭션 t에서의 소속도 최솟값을 합산)`,
    features: `<p><strong>장점</strong> — 구간 경계에서의 정보 손실을 줄이고, "가격이 대체로 비쌈"처럼 사람이 이해하기 쉬운 규칙을 생성합니다.</p><p><strong>단점</strong> — 소속 함수의 형태와 파라미터를 설계자가 정해야 하므로 주관성이 개입되고, 계산 복잡도가 일반 연관규칙보다 높습니다.</p>`,
    applications: `<p>고객 나이·소득 등 수치형 속성이 섞인 소매 데이터, 센서 값처럼 애매한 경계를 갖는 데이터의 연관규칙 탐색에 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, 주로 R의 퍼지 연관규칙 패키지나 학술 구현을 통해 활용됩니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'multi-dimensional-association-rules',
    category: 'unsup',
    subcategory: 'association',
    title: '다차원 연관규칙 (Multi-dimensional Association Rules)',
    subtitle: '하나의 항목 차원이 아니라 여러 속성(차원)을 동시에 조건절·결과절에 포함하는 연관규칙',
    overview: `<p>전통적 연관규칙은 "항목을 샀다/안 샀다"라는 단일 차원(booean itemset)만 다루지만, 다차원 연관규칙은 나이·직업·거주지역처럼 서로 다른 속성(차원)을 함께 조건절과 결과절에 담습니다. 예를 들어 "나이=20대 이고 직업=학생이면 노트북을 구매한다"처럼 여러 술어(predicate)가 결합된 규칙 형태를 다룹니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 단일 속성만으로는 드러나지 않는 속성 간 상호작용을 포착해 더 풍부한 패턴을 발견할 수 있습니다.</p><p><strong>단점</strong> — 차원(속성) 수가 늘어날수록 조합 폭발이 심해지고, 무의미하거나 중복된 규칙이 함께 생성되기 쉽습니다.</p>`,
    applications: `<p>고객 관계 관리(CRM) 데이터베이스에서 인구통계 속성과 구매 항목을 함께 분석하거나, 관계형 데이터베이스의 여러 컬럼을 결합한 패턴 탐색에 사용됩니다. scikit-learn/mlxtend에는 전용 구현이 없으며, 관계형 데이터마이닝 도구나 학술 프로토타입을 통해 다뤄집니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'multi-level-association-rules',
    category: 'unsup',
    subcategory: 'association',
    title: '다계층 연관규칙 (Multi-level Association Rules)',
    subtitle: '개념 계층(concept hierarchy)의 여러 추상화 수준을 오가며 연관규칙을 발견하는 기법',
    overview: `<p>Han과 Fu가 1995년 VLDB에서 제안한 개념으로, "우유"와 "저지방 우유"처럼 상위-하위 개념 계층을 가진 데이터에서 최상위 범주 수준부터 세부 브랜드 수준까지 여러 층위를 오가며 규칙을 찾습니다. 계층의 하위로 내려갈수록 개별 항목의 지지도가 작아지는 문제를 보완하기 위해 계층별로 서로 다른 최소 지지도 임계값을 적용하는 경우가 많습니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 너무 구체적이라 지지도가 낮게 나오는 항목도 상위 개념 수준에서는 유의미한 규칙으로 드러날 수 있습니다.</p><p><strong>단점</strong> — 개념 계층을 사전에 구축해야 하고, 계층 간 중복되거나 자명한 규칙(예: 상위 규칙에서 자동으로 유도되는 하위 규칙)을 걸러내는 후처리가 필요합니다.</p>`,
    applications: `<p>상품 분류 체계(대분류-중분류-소분류)를 가진 유통 데이터, 의약품 성분 계층 등에서 다양한 추상화 수준의 구매·처방 패턴을 찾을 때 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, 계층 정보를 반영한 확장 Apriori 계열 알고리즘으로 별도 구현되어야 합니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'negative-association-rules',
    category: 'unsup',
    subcategory: 'association',
    title: '부정 연관규칙 (Negative Association Rules)',
    subtitle: '"A를 사면 B를 사지 않는다"처럼 항목의 부재(negation) 관계를 다루는 연관규칙',
    overview: `<p>Savasere, Omiecinski, Navathe가 1998년에 제안한 개념으로, 일반 연관규칙이 "함께 등장"하는 양의 상관관계만 다루는 것과 달리 "함께 등장하지 않는" 음의 상관관계도 유의미한 지식으로 봅니다. 두 항목이 각각은 자주 등장하지만 동시에는 거의 등장하지 않는 경우를 찾아내며, 이때는 단순 지지도보다 상관계수 기반 척도가 필요합니다.</p>`,
    formula: `PS(A,B) = P(A &#8746; B) &#8722; P(A)P(B)  (Piatetsky-Shapiro 척도, 값이 음수이면 부정적 연관성)`,
    features: `<p><strong>장점</strong> — 대체재 관계, 상호 배타적 구매 패턴 등 일반 연관규칙으로는 드러나지 않는 정보를 포착합니다.</p><p><strong>단점</strong> — 두 항목이 모두 드물게 등장하는 경우와 실제로 배타적인 경우를 구분하기 어려워 잘못된 부정 규칙(허위 상관)이 생기기 쉽습니다.</p>`,
    applications: `<p>서로 대체 가능한 상품(예: 특정 브랜드 간 구매 배타성) 탐지, 이상 패턴 탐지의 보조 지표로 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, 학술 구현체나 확장 Apriori 코드로 다뤄집니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'quantitative-association-rules',
    category: 'unsup',
    subcategory: 'association',
    title: '정량적 연관규칙 (Quantitative Association Rules)',
    subtitle: '수치형 속성을 구간으로 분할한 뒤 그 구간들 사이의 연관규칙을 찾는 기법',
    overview: `<p>Srikant와 Agrawal이 1996년 SIGMOD에서 제안한 방법으로, 나이·수량처럼 연속적인 정량적 속성을 등간격 또는 등빈도 구간으로 분할한 뒤 이 구간들을 마치 범주형 항목처럼 취급해 Apriori류 알고리즘을 적용합니다. 예를 들어 "나이&#8712;[30,39] 이고 결혼여부=기혼이면 보유차량수&#8712;[2,3]"과 같은 규칙을 도출합니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 수치형 데이터를 별도 전처리 없이 기존 항목집합 마이닝 틀 안에서 다룰 수 있습니다.</p><p><strong>단점</strong> — 구간을 너무 잘게 나누면 지지도가 낮아지고, 너무 크게 나누면 흥미로운 세부 패턴을 놓치는 구간 경계(interval-boundary) 문제가 있습니다.</p>`,
    applications: `<p>인구통계·거래금액 등 수치형 속성이 포함된 데이터베이스에서 구간화 후 연관규칙을 도출할 때 사용되며, 실무에서는 사전에 pandas의 <code>cut</code>/<code>qcut</code> 등으로 구간화한 뒤 mlxtend의 Apriori/FP-Growth를 적용하는 방식으로 흔히 대체됩니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'rare-association-rules',
    category: 'unsup',
    subcategory: 'association',
    title: '희소 연관규칙 (Rare Association Rules)',
    subtitle: '지지도는 낮지만 확신도(신뢰도)는 높은, 드물게 발생하는 항목집합에 대한 연관규칙',
    overview: `<p>일반적인 최소 지지도 임계값을 그대로 적용하면 드물게 발생하지만 의미 있는 조합(희소 항목집합)이 걸러져 버리는 문제를 해결하기 위한 접근입니다. Liu, Hsu, Ma의 MSApriori(1999)처럼 항목별로 서로 다른 최소 지지도(multiple support)를 두거나, 희소하면서도 신뢰도가 높은 규칙만 별도로 탐색하는 방식을 사용합니다.</p>`,
    formula: `minsup&#8342; &#8804; support(X) 이면서 support(X) &lt; minsup(일반 임계값)인 항목집합 X를 희소 빈발 항목집합으로 정의`,
    features: `<p><strong>장점</strong> — 희귀 질병 조합, 드문 사기 패턴처럼 발생 빈도는 낮지만 임팩트가 큰 사건을 놓치지 않고 포착합니다.</p><p><strong>단점</strong> — 임계값을 낮추면 잡음성 규칙이 급증해 진짜 흥미로운 희소 패턴과 우연의 일치를 구분하기 어려워집니다.</p>`,
    applications: `<p>희귀 질환-증상 조합 탐지, 저빈도 금융사기 패턴 탐지, 소량 다품종 판매 데이터의 특이 조합 발견 등에 사용됩니다. scikit-learn/mlxtend에는 표준 구현이 없으며, MSApriori 등은 별도 학술 구현체를 통해 활용됩니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'spatial-association-rules',
    category: 'unsup',
    subcategory: 'association',
    title: '공간 연관규칙 (Spatial Association Rules)',
    subtitle: '인접·포함·교차 같은 공간적 관계를 조건절/결과절에 담아 지리 데이터에서 패턴을 찾는 연관규칙',
    overview: `<p>Koperski와 Han이 1995년에 제안한 개념으로, 일반 항목 대신 "근접(close_to)", "포함(contained_in)", "인접(adjacent_to)" 같은 공간 술어를 이용해 지리정보(GIS) 데이터에서 규칙을 찾습니다. 예를 들어 "큰 마을은 대개 고속도로에 인접해 있다"처럼 공간 객체 간의 위상·거리 관계를 다룹니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 좌표·경계 등 공간 정보를 직접 반영해 일반 속성만으로는 표현할 수 없는 지리적 패턴을 발견합니다.</p><p><strong>단점</strong> — 공간 술어 계산(거리, 위상 관계 판정) 자체의 연산 비용이 크고, 공간 해상도(세밀한 격자 vs. 넓은 지역)에 따라 결과가 민감하게 달라집니다.</p>`,
    applications: `<p>도시계획, 부동산 입지 분석, 역학 데이터의 지리적 군집·인접 패턴 탐색 등 GIS 기반 의사결정에 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, GIS 전용 공간 데이터마이닝 도구나 학술 구현으로 다뤄집니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'temporal-association-rules',
    category: 'unsup',
    subcategory: 'association',
    title: '시간적 연관규칙 (Temporal Association Rules)',
    subtitle: '규칙의 지지도·신뢰도가 특정 시간 구간에서만 유효함을 함께 표현하는 연관규칙',
    overview: `<p>Ale와 Rossi가 2000년에 제안한 개념으로, 거래에 타임스탬프가 있다는 점을 활용해 규칙이 항상 성립하는 것이 아니라 특정 생애주기(lifespan)나 계절·요일 구간에서만 강하게 성립함을 반영합니다. Apriori를 시간 구간별로 적용하거나, 각 규칙에 유효 구간을 함께 마이닝하는 방식으로 확장합니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — "여름에만 함께 팔리는 상품" 같이 시간에 따라 변하는 연관성을 포착해 정적 연관규칙이 놓치는 패턴을 잡아냅니다.</p><p><strong>단점</strong> — 시간 구간을 어떻게 나누느냐에 따라 결과가 크게 달라지고, 구간이 세분화될수록 각 구간의 데이터 양이 줄어 통계적 신뢰도가 낮아집니다.</p>`,
    applications: `<p>계절성 상품 판매 분석, 요일·시간대별 웹 로그 패턴 분석, 프로모션 효과의 시간대별 검증 등에 사용됩니다. scikit-learn/mlxtend에는 전용 구현이 없으며, 시간 구간으로 데이터를 분할한 뒤 mlxtend의 Apriori/FP-Growth를 반복 적용하는 방식으로 흔히 대체됩니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'bide',
    category: 'unsup',
    subcategory: 'association',
    title: 'BIDE (BI-Directional Extension)',
    subtitle: '후보를 유지하지 않고 양방향 확장 검사만으로 폐쇄 순차 패턴을 찾는 알고리즘',
    overview: `<p>Wang과 Han이 2004년 ICDE에서 발표한 알고리즘으로, 순방향 확장은 접두사 패턴을 성장시키면서 동시에 폐쇄 여부를 검사하고, 역방향 확장(BackScan)은 이미 찾은 패턴의 폐쇄 여부를 검사하면서 탐색 공간을 가지치기합니다. CloSpan처럼 후보 폐쇄 패턴 집합을 별도로 유지하지 않아도 되어 메모리 효율이 뛰어납니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 후보 유지(candidate maintenance)가 필요 없어 CloSpan보다 메모리 효율이 좋고, BackScan 가지치기로 탐색 공간을 깊이 줄입니다.</p><p><strong>단점</strong> — 양방향 확장 검사 로직이 복잡해 구현 난이도가 높고, 매우 긴 시퀀스에서는 역방향 검사 비용이 커질 수 있습니다.</p>`,
    applications: `<p>웹 로그·유전자 서열처럼 긴 시퀀스에서 중복 없는 대표 패턴(폐쇄 순차 패턴)만 압축해 찾고 싶을 때 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, SPMF 라이브러리가 BIDE/BIDE+ 구현을 제공합니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'clospan',
    category: 'unsup',
    subcategory: 'association',
    title: 'CloSpan (CLOsed Sequential pattern mining)',
    subtitle: '후보 폐쇄 시퀀스를 먼저 생성한 뒤 사후 가지치기로 걸러내는 폐쇄 순차 패턴 마이닝',
    overview: `<p>Yan, Han, Afshar가 2003년 SDM에서 제안한 알고리즘으로, 마이닝 과정을 두 단계로 나눕니다. 1단계에서는 후보 폐쇄 시퀀스 집합을 접두사 시퀀스 격자(lattice)에 저장하며 생성하고, 2단계에서 동일 지지도를 갖는 상위집합이 존재하는 비폐쇄 시퀀스를 사후에 제거합니다. 같은 표현력을 유지하면서도 발견되는 시퀀스 수를 크게 줄여 PrefixSpan보다 긴 시퀀스에서 더 빠르게 동작합니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 폐쇄 시퀀스만 남겨 결과 수를 크게 줄이면서도 정보 손실이 없고, 긴 시퀀스 마이닝에서 PrefixSpan보다 빠릅니다.</p><p><strong>단점</strong> — 후보를 먼저 생성하고 나중에 걸러내는 candidate maintenance-and-test 방식이라 메모리 사용량이 BIDE보다 많습니다.</p>`,
    applications: `<p>고객 행동 시퀀스, 웹 클릭스트림 등에서 중복 없는 대표 순차 패턴을 찾을 때 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, SPMF 라이브러리에서 CloSpan 구현을 제공합니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'freespan',
    category: 'unsup',
    subcategory: 'association',
    title: 'FreeSpan (FREquent pattern-projected Sequential pattern mining)',
    subtitle: '빈발 패턴 정보로 프로젝션된 부분 데이터베이스를 재귀적으로 좁혀가며 순차 패턴을 찾는 초기 패턴 성장 알고리즘',
    overview: `<p>Han, Pei 등이 2000년 KDD에서 제안한 알고리즘으로, 순차 패턴 마이닝에 빈발 패턴 마이닝과 프로젝션 데이터베이스 개념을 처음 결합했습니다. 빈발 항목 정보를 이용해 검색 공간을 점점 좁혀가는 프로젝션 데이터베이스를 재귀적으로 만들어 후보 시퀀스 생성 없이 패턴을 확장하며, Apriori 기반의 GSP보다 훨씬 적은 조합을 검사하고 더 빠르게 동작함을 보였습니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 후보 생성 부담을 크게 줄이고 GSP보다 검사하는 부분열 조합 수가 훨씬 적어 빠릅니다.</p><p><strong>단점</strong> — 이후 제안된 PrefixSpan에 비해 프로젝션 데이터베이스가 상대적으로 크고 비효율적이어서 현재는 PrefixSpan으로 대체되는 경우가 많습니다.</p>`,
    applications: `<p>순차 패턴 마이닝의 프로젝션 기반 접근을 이해하기 위한 개념적·역사적 의미가 크며, 실무에서는 후속작인 PrefixSpan이 더 널리 쓰입니다. scikit-learn/mlxtend에는 구현이 없고, SPMF 등 학술 패턴 마이닝 라이브러리에서 다뤄집니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'gsp',
    category: 'unsup',
    subcategory: 'association',
    title: 'GSP (Generalized Sequential Patterns)',
    subtitle: 'Apriori의 후보 생성-검사 방식을 시간 제약 조건과 함께 시퀀스 데이터로 확장한 알고리즘',
    overview: `<p>Srikant와 Agrawal이 1996년에 제안한 알고리즘으로, Apriori와 마찬가지로 길이 k 빈발 시퀀스로부터 길이 k+1 후보 시퀀스를 생성하고 데이터베이스를 스캔해 지지도를 검사하는 과정을 반복합니다. 최대 간격(max-gap), 최소 간격(min-gap), 슬라이딩 윈도우(sliding window) 같은 시간 제약과 계층 정보(taxonomy)까지 지원하는 일반화된 프레임워크입니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 시간 제약과 개념 계층을 함께 지원해 표현력이 뛰어나고, Apriori와 유사한 구조라 이해하기 쉽습니다.</p><p><strong>단점</strong> — Apriori와 같은 한계로 후보 시퀀스가 폭증하고 데이터베이스를 반복 스캔해야 해 PrefixSpan·SPADE 등 패턴 성장 방식보다 느립니다.</p>`,
    applications: `<p>웹 사용 패턴 분석, 유전자 서열, 고객 구매 순서 분석 등 시간 제약이 있는 순차 패턴 마이닝의 고전적 표준으로 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, SPMF 라이브러리에서 GSP 구현을 제공합니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'prefixspan',
    category: 'unsup',
    subcategory: 'association',
    title: 'PrefixSpan (Prefix-projected Sequential pattern mining)',
    subtitle: '접두사를 기준으로 프로젝션된 부분 데이터베이스를 재귀적으로 탐색하는 패턴 성장 기반 순차 패턴 마이닝',
    overview: `<p>Pei, Han 등이 2001년에 제안한 알고리즘으로, 후보 시퀀스를 생성하지 않고 짧은 빈발 접두사를 찾은 뒤, 그 접두사로 시작하는 트랜잭션들의 나머지 부분(postfix)만 모은 프로젝션 데이터베이스에서 재귀적으로 접두사를 확장해 나갑니다. GSP·FreeSpan보다 검사해야 할 후보 수와 프로젝션 크기가 작아 순차 패턴 마이닝의 사실상 표준 알고리즘으로 자리잡았습니다.</p>`,
    formula: `&#945;-projected DB = { s의 postfix | s &#8712; DB, &#945;가 s의 부분열(subsequence)인 경우 }`,
    features: `<p><strong>장점</strong> — 후보 생성이 없고 프로젝션 데이터베이스가 반복적으로 작아져 GSP·FreeSpan보다 빠르고 확장성이 좋습니다.</p><p><strong>단점</strong> — 프로젝션 데이터베이스를 물리적으로 반복 생성하는 경우 메모리·I/O 비용이 커질 수 있어 유사 프로젝션(pseudo-projection) 등 최적화가 필요합니다.</p>`,
    applications: `<p>웹 클릭스트림, 고객 구매 이력, 생물학적 서열 분석 등 순차 패턴 마이닝 전반에서 가장 널리 쓰이는 알고리즘입니다. scikit-learn/mlxtend에는 구현이 없으며, SPMF와 다양한 오픈소스 구현체(Python 포함)를 통해 사용할 수 있습니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'spade',
    category: 'unsup',
    subcategory: 'association',
    title: 'SPADE (Sequential PAttern Discovery using Equivalence classes)',
    subtitle: '수직 id-list 형식과 동등 클래스 격자 탐색으로 후보를 3회 이하의 스캔에 찾는 순차 패턴 마이닝',
    overview: `<p>Zaki가 2001년에 제안한 알고리즘으로, Eclat과 유사하게 각 시퀀스 항목에 대해 (시퀀스ID, 이벤트ID) 쌍의 id-list를 수직 형식으로 구성합니다. 접두사를 공유하는 시퀀스들을 동등 클래스로 묶어 격자(lattice)를 이루고, id-list의 시간적 조인(temporal join)만으로 지지도를 계산해 데이터베이스를 최대 3번만 스캔하면 전체 빈발 순차 패턴을 찾을 수 있습니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 데이터베이스 스캔 횟수가 매우 적고 격자 기반 탐색으로 병렬화가 쉬워 대용량 데이터에 적합합니다.</p><p><strong>단점</strong> — id-list가 커지면 메모리 사용량이 늘어나고, 매우 긴 시퀀스에서는 조인 연산 비용이 커질 수 있습니다.</p>`,
    applications: `<p>대용량 트랜잭션·이벤트 로그에서 순차 패턴을 빠르게 찾아야 하는 상황에 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, SPMF 라이브러리에서 SPADE 구현을 제공합니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'spam-sequential',
    category: 'unsup',
    subcategory: 'association',
    title: 'SPAM (Sequential PAttern Mining using bitmap representation)',
    subtitle: '수직 비트맵 표현으로 지지도를 빠르게 계산하는 깊이 우선 순차 패턴 마이닝',
    overview: `<p>Ayres, Gehrke, Yiu, Flannick이 2002년에 제안한 알고리즘으로, 데이터베이스를 한 번 스캔해 각 항목에 대한 수직 비트맵을 구성합니다. 이 비트맵에서 시퀀스의 각 원소에 대응하는 비트가 설정되며, 이를 이용해 S-step(시퀀스 확장)과 I-step(항목 확장)이라는 두 가지 확장 연산으로 깊이 우선 탐색을 수행하고, 비트 연산만으로 지지도를 매우 빠르게 계산합니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 비트 연산 기반 지지도 계산이 매우 빠르고, 별도의 데이터베이스 재스캔이 필요 없습니다.</p><p><strong>단점</strong> — 모든 항목에 대한 비트맵을 메모리에 유지해야 해서 항목 종류가 많거나 시퀀스가 길면 메모리 사용량이 크게 증가합니다.</p>`,
    applications: `<p>대량의 짧고 조밀한 시퀀스 데이터에서 최장 빈발 패턴까지 빠르게 찾아야 하는 경우에 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, SPMF 라이브러리에서 SPAM 구현을 제공합니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'episode-mining',
    category: 'unsup',
    subcategory: 'association',
    title: '에피소드 마이닝 (Episode Mining)',
    subtitle: '하나의 긴 이벤트 시퀀스 안에서 시간 윈도우 내 자주 등장하는 부분 순서 패턴(에피소드)을 찾는 기법',
    overview: `<p>Mannila, Toivonen, Verkamo가 1997년에 제안한 개념으로, 여러 개의 독립된 트랜잭션이 아니라 하나의 연속된 이벤트 스트림에서 정해진 폭(width)의 시간 윈도우 안에 자주 함께 나타나는 이벤트 조합(에피소드)을 찾습니다. 에피소드는 이벤트 간 순서를 요구하지 않는 병렬(parallel) 에피소드와, 정해진 순서를 요구하는 직렬(serial) 에피소드로 구분됩니다.</p>`,
    formula: `frequency(&#945;) = |{윈도우(폭 w) : 에피소드 &#945;를 포함} | / 전체 윈도우 수  &#8805; minfreq`,
    features: `<p><strong>장점</strong> — 트랜잭션 경계가 없는 연속 이벤트 스트림에서도 시간 윈도우만으로 자연스럽게 패턴을 정의할 수 있습니다.</p><p><strong>단점</strong> — 윈도우 폭 설정에 결과가 민감하고, 이벤트 발생 빈도가 매우 높은 스트림에서는 윈도우 수 자체가 방대해질 수 있습니다.</p>`,
    applications: `<p>통신 네트워크 경보 로그, 산업 설비의 센서 이벤트 로그에서 장애로 이어지는 전조 패턴을 찾는 등 시계열 이벤트 분석에 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, SPMF 등 전문 패턴 마이닝 라이브러리에서 다뤄집니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'graph-pattern-mining',
    category: 'unsup',
    subcategory: 'association',
    title: '그래프 패턴 마이닝 (Graph Pattern Mining)',
    subtitle: '그래프로 표현된 데이터베이스에서 자주 등장하는 부분 그래프(subgraph)를 찾는 기법',
    overview: `<p>대표 알고리즘인 gSpan(Yan & Han, 2002)은 각 그래프를 깊이 우선 탐색(DFS) 코드라는 표준화된 문자열로 표현하고, 이 DFS 코드 중 사전식으로 최소인 것을 정준 형태(canonical form)로 채택합니다. 이를 통해 그래프 동형사상(isomorphism) 검사 없이도 중복 없이 빈발 부분 그래프를 확장·열거할 수 있습니다.</p>`,
    formula: `min DFS-code(G)를 정준 레이블로 채택하여 그래프 동형사상 중복 검사를 회피`,
    features: `<p><strong>장점</strong> — 후보 부분 그래프 생성을 정준 형태 기준으로 체계화해 중복 탐색을 크게 줄입니다.</p><p><strong>단점</strong> — 그래프 동형사상 판정 자체가 NP류 문제라 그래프 크기·개수가 커지면 여전히 계산 비용이 급격히 늘어납니다.</p>`,
    applications: `<p>화합물 구조에서 공통 부분구조 탐색(신약 개발), 소셜 네트워크·지식 그래프에서 반복되는 연결 패턴 탐색 등에 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, gSpan 등은 별도 그래프 마이닝 라이브러리(SPMF 등)로 제공됩니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'stream-pattern-mining',
    category: 'unsup',
    subcategory: 'association',
    title: '스트림 패턴 마이닝 (Stream Pattern Mining)',
    subtitle: '한 번에 지나가는 무한 데이터 스트림에서 최근 패턴을 근사적으로 유지·갱신하는 기법',
    overview: `<p>대표적으로 Giannella, Han 등이 제안한 FP-stream은 FP-트리와 틸티드-타임 윈도우(tilted-time window) 모델을 결합해, 최근 시간대는 세밀한 granularity로, 오래된 시간대는 성긴 granularity로 빈발 패턴의 지지도 이력을 유지합니다. 데이터를 저장하지 않고 한 번만 훑으면서도 여러 시간 granularity에서의 질의에 오차 한계 내로 답할 수 있습니다.</p>`,
    formula: `틸티드-타임 윈도우 granularity: 최근 구간일수록 세밀, 2&#7522;배 간격으로 성글어지는 계층 구조`,
    features: `<p><strong>장점</strong> — 전체 스트림을 저장하지 않고도 압축된 요약 구조만으로 시간에 따라 변하는 패턴을 근사적으로 추적할 수 있습니다.</p><p><strong>단점</strong> — 정확한 결과가 아닌 오차 한계 내 근사 결과이며, 개념 변화(concept drift)가 빠른 스트림에서는 오래된 패턴 정보의 신뢰도가 떨어집니다.</p>`,
    applications: `<p>실시간 네트워크 트래픽 모니터링, 온라인 쇼핑몰의 실시간 인기 조합 추적처럼 무한히 유입되는 데이터에서 최신 트렌드를 파악할 때 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, 스트림 마이닝 전용 라이브러리(MOA 등)에서 유사 기법을 제공합니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'tree-pattern-mining',
    category: 'unsup',
    subcategory: 'association',
    title: '트리 패턴 마이닝 (Tree Pattern Mining)',
    subtitle: '레이블이 있는 순서 트리 집합(포레스트)에서 자주 등장하는 부분 트리를 찾는 기법',
    overview: `<p>대표 알고리즘인 TreeMiner(Zaki, 2002)는 스코프 리스트(scope-list)라는 자료구조를 이용해 포레스트(rooted, labeled, ordered tree들의 집합) 안에서 임베디드(embedded) 부분 트리를 효율적으로 열거합니다. 패턴 매칭 방식보다 4~20배 빠르며 확장성이 좋아, 이후 순서 없는 트리까지 다루는 SLEUTH로 확장되었습니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 스코프 리스트를 이용해 트리 임베딩 여부를 빠르게 판정하며, 확장성이 뛰어납니다.</p><p><strong>단점</strong> — 트리의 순서·레이블 제약에 따라 알고리즘 변형이 필요하고, 매우 큰 포레스트에서는 스코프 리스트 크기가 커질 수 있습니다.</p>`,
    applications: `<p>웹사이트 방문 경로(트리 구조 웹 로그) 분석, XML/반정형 문서에서 반복되는 구조 패턴 탐색, 생물정보학의 계통수 분석 등에 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, Zaki 연구실이 공개한 TreeMiner 구현과 SPMF에서 관련 기법을 제공합니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'utility-mining',
    category: 'unsup',
    subcategory: 'association',
    title: '효용 마이닝 (Utility Mining)',
    subtitle: '단순 발생 빈도가 아니라 수량과 단가를 반영한 실질적 가치(효용)가 높은 항목집합을 찾는 기법',
    overview: `<p>빈도만 세는 전통적 연관규칙 마이닝은 "저가·소량이지만 자주 팔리는 상품"에는 강하지만 "고가·소량으로 팔려도 이익 기여도가 큰 상품 조합"은 놓치는 한계가 있습니다. 고효용 항목집합 마이닝(High Utility Itemset Mining)은 각 항목에 수량(내부 효용)과 단가(외부 효용)를 부여해 항목집합의 총 효용을 계산하고, 이 값이 임계값을 넘는 항목집합만 찾습니다. Tseng 등이 제안한 UP-Growth는 FP-트리와 유사한 UP-Tree 구조로 두 번의 스캔만으로 효율적으로 후보를 생성합니다.</p>`,
    formula: `u(X) = &#8721;&#8348;&#8839;&#8416; &#8721;&#8305;&#8712;&#8416; u(i,T)  (T: X를 포함하는 트랜잭션, u(i,T): 트랜잭션 T에서 항목 i의 효용) — u(X) &#8805; minutil이면 고효용 항목집합`,
    features: `<p><strong>장점</strong> — 판매량뿐 아니라 이익·비용 등 비즈니스 가치를 직접 반영해 실무적으로 더 의미 있는 조합을 찾습니다.</p><p><strong>단점</strong> — 효용은 지지도와 달리 하향 폐쇄성(anti-monotone)을 만족하지 않아 가지치기가 까다롭고, 이를 보완하는 상한(upper-bound) 기법과 별도 자료구조가 필요합니다.</p>`,
    applications: `<p>소매업의 고수익 상품 조합 발굴, 재고 관리에서 이익 기여도가 큰 묶음 상품 기획 등에 사용됩니다. scikit-learn/mlxtend에는 구현이 없으며, SPMF 라이브러리가 UP-Growth를 포함한 다양한 고효용 항목집합 마이닝 알고리즘을 제공합니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'dictionary-learning',
    category: 'unsup',
    subcategory: 'dim-reduction',
    title: '사전 학습 (Dictionary Learning)',
    subtitle: '데이터를 소수의 원자(atom) 조합으로 희소하게 표현하는 과완전 사전을 데이터로부터 직접 학습하는 기법',
    overview: `<p>고정된 웨이블릿·푸리에 기저 대신, 데이터 자체로부터 신호를 잘 표현하는 기저 벡터들의 집합(사전, dictionary)을 학습합니다. 각 신호는 사전의 소수 원자만을 조합한 희소 표현(sparse code)으로 근사되며, 사전 학습과 희소 부호화를 번갈아 최적화합니다.</p>`,
    formula: `min&#8337;,&#7615; &#8721;&#8305; ||x&#7522; &#8722; D&#945;&#7522;||&#178;&#8322; + &#955;||&#945;&#7522;||&#8321;  (D: 사전, &#945;&#7522;: 희소 계수)`,
    features: `<p><strong>장점</strong> — 데이터에 특화된 기저를 학습해 고정 기저보다 적은 원자로도 신호를 잘 표현하고, 잡음 제거·복원에 강합니다.</p><p><strong>단점</strong> — 사전 크기와 희소성 정도(하이퍼파라미터)에 결과가 민감하고, 대규모 데이터에서는 학습 비용이 큽니다.</p>`,
    applications: `<p>이미지 잡음 제거, 영상 압축, 얼굴 인식 전처리 등에 사용됩니다. scikit-learn의 <code>DictionaryLearning</code> 클래스로 제공되며, 얼굴 데이터셋 분해 예제에서 NMF·PCA 등과 함께 비교됩니다.</p>`,
    sklearnFunction: 'DictionaryLearning',
    sklearnGuideURL: 'https://scikit-learn.org/stable/modules/decomposition.html#dictionary-learning',
    sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.DictionaryLearning.html',
    sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/decomposition/plot_image_denoising.html',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'factor-analysis',
    category: 'unsup',
    subcategory: 'dim-reduction',
    title: '요인 분석 (FA, Factor Analysis)',
    subtitle: '관측 변수들의 공분산을 소수의 잠재 요인과 변수별 고유 잡음으로 설명하는 확률적 선형 모델',
    overview: `<p>PCA가 모든 변수에 동일한 분산의 등방성(isotropic) 잡음을 가정하는 것과 달리, 요인 분석은 변수마다 서로 다른 잡음 분산(이분산, heteroscedastic noise)을 허용합니다. 관측 변수를 소수의 공통 잠재 요인의 선형 결합과 변수 고유의 오차항으로 분해해, 변수 간 공분산 구조를 설명하려 합니다.</p>`,
    formula: `x = &#923;f + &#949;,  Cov(x) = &#923;&#923;&#7488; + &#936;  (&#936;: 변수별 대각 잡음 공분산 행렬)`,
    features: `<p><strong>장점</strong> — 변수별로 다른 잡음 수준을 반영할 수 있어 이질적인 측정 오차를 가진 데이터에 PCA보다 적합합니다.</p><p><strong>단점</strong> — 요인 수를 사전에 정해야 하고, 회전(rotation)에 따라 해석이 달라지는 비유일성(non-uniqueness) 문제가 있습니다.</p>`,
    applications: `<p>심리검사·설문 문항에서 잠재 성향(요인) 추출, 금융 자산 수익률의 공통 위험요인 분석 등에 사용됩니다. scikit-learn의 <code>FactorAnalysis</code> 클래스로 제공되며, varimax 회전을 적용한 시각화 예제도 제공됩니다.</p>`,
    sklearnFunction: 'FactorAnalysis',
    sklearnGuideURL: 'https://scikit-learn.org/stable/modules/decomposition.html#factor-analysis',
    sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.FactorAnalysis.html',
    sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/decomposition/plot_varimax_fa.html',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'fastica',
    category: 'unsup',
    subcategory: 'dim-reduction',
    title: 'FastICA',
    subtitle: '비가우시안성(negentropy)을 최대화하는 고정점 반복으로 독립성분분석을 빠르게 계산하는 알고리즘',
    overview: `<p>Hyvärinen과 Oja가 제안한 ICA의 대표적 실전 구현으로, 혼합된 신호에서 통계적으로 최대한 독립적인 성분을 찾기 위해 음의 엔트로피(negentropy) 근사치를 목적함수로 삼아 고정점 반복(fixed-point iteration)으로 빠르게 수렴시킵니다. 사전에 백색화(whitening) 전처리를 거친 뒤 각 성분을 순차적으로 또는 병렬로 추출합니다.</p>`,
    formula: `maximize J(w) &#8776; [E{G(w&#7488;x)} &#8722; E{G(v)}]&#178;  (G: 비이차 함수, v: 표준정규 확률변수)`,
    features: `<p><strong>장점</strong> — 다른 ICA 알고리즘보다 수렴 속도가 빠르고 구현이 간결하며 널리 검증되어 있습니다.</p><p><strong>단점</strong> — 성분 개수와 부호·크기가 정해지지 않는 비유일성이 있고, 초기값에 따라 다른 국소해로 수렴할 수 있습니다.</p>`,
    applications: `<p>혼합된 오디오 신호의 음원 분리(칵테일 파티 문제), 뇌파(EEG)·기능적 자기공명영상(fMRI) 신호에서 잡음원 분리 등에 사용됩니다. scikit-learn의 <code>FastICA</code> 클래스로 제공되며, 신호 분리 예제가 공식 문서에 포함되어 있습니다.</p>`,
    sklearnFunction: 'FastICA',
    sklearnGuideURL: 'https://scikit-learn.org/stable/modules/decomposition.html#independent-component-analysis-ica',
    sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.FastICA.html',
    sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/decomposition/plot_ica_blind_source_separation.html',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'gaussian-random-projection',
    category: 'unsup',
    subcategory: 'dim-reduction',
    title: '가우시안 무작위 투영 (Gaussian Random Projection)',
    subtitle: '원소가 정규분포에서 뽑힌 무작위 투영 행렬로 고차원 데이터를 저차원에 근사적으로 사영하는 기법',
    overview: `<p>Johnson-Lindenstrauss 보조정리에 근거해, N(0, 1/n_components) 분포에서 뽑은 원소로 이루어진 무작위 행렬을 데이터에 곱하는 것만으로도 점들 사이의 쌍별 거리를 확률적으로 보존하며 차원을 축소할 수 있음을 이용합니다. 데이터에 대한 학습 없이 무작위 행렬만 생성하면 되어 계산이 매우 가볍습니다.</p>`,
    formula: `(1&#8722;&#949;)||u&#8722;v||&#178; &#8804; ||Ru&#8722;Rv||&#178; &#8804; (1+&#949;)||u&#8722;v||&#178;  (Johnson-Lindenstrauss 보조정리)`,
    features: `<p><strong>장점</strong> — 데이터를 보지 않고도 투영 행렬을 만들 수 있어 매우 빠르고, 초고차원 희소 데이터에도 적용 가능합니다.</p><p><strong>단점</strong> — PCA처럼 분산을 최대로 보존하는 방향을 찾는 것이 아니라 무작위성에 의존하므로, 같은 차원 수에서 정보 보존력은 PCA보다 낮을 수 있습니다.</p>`,
    applications: `<p>텍스트의 초고차원 TF-IDF 벡터, 대규모 희소 특징 행렬의 사전 차원 축소 등 학습 없이 빠르게 차원을 줄여야 하는 대용량 파이프라인에 사용됩니다. scikit-learn의 <code>GaussianRandomProjection</code> 클래스로 제공됩니다.</p>`,
    sklearnFunction: 'GaussianRandomProjection',
    sklearnGuideURL: 'https://scikit-learn.org/stable/modules/random_projection.html',
    sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.random_projection.GaussianRandomProjection.html',
    sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_johnson_lindenstrauss_bound.html',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'ica',
    category: 'unsup',
    subcategory: 'dim-reduction',
    title: '독립성분분석 (ICA, Independent Component Analysis)',
    subtitle: '관측된 혼합 신호를 통계적으로 서로 독립인 잠재 성분들의 선형 결합으로 분리하는 기법',
    overview: `<p>PCA가 성분 간 비상관(uncorrelated)만을 요구하는 것과 달리, ICA는 성분들이 통계적으로 독립(independent)일 것을 요구하며, 이를 위해 가우시안이 아닌 분포(비가우시안성)를 극대화하는 방향으로 성분을 찾습니다. "여러 마이크로 녹음된 혼합 음성에서 각 화자의 음성을 분리"하는 칵테일 파티 문제가 대표적인 동기입니다.</p>`,
    formula: `x = As  (A: 알 수 없는 혼합 행렬, s: 독립 성분들) &#8658; W = A&#8315;&#185;를 추정하여 s &#8776; Wx 복원`,
    features: `<p><strong>장점</strong> — 성분 간 통계적 독립성을 직접 추구하므로 PCA로는 분리되지 않는 원천 신호를 구분해낼 수 있습니다.</p><p><strong>단점</strong> — 가우시안 성분이 2개 이상이면 분리가 불가능하고, 성분의 순서와 부호가 정해지지 않는 비유일성이 있습니다.</p>`,
    applications: `<p>음원 분리, 생체신호(EEG/fMRI) 잡음 제거, 이미지에서 조명·반사 성분 분리 등에 사용됩니다. scikit-learn에서는 <code>FastICA</code> 클래스가 ICA의 실전 구현체로 제공됩니다.</p>`,
    sklearnFunction: 'FastICA',
    sklearnGuideURL: 'https://scikit-learn.org/stable/modules/decomposition.html#independent-component-analysis-ica',
    sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.FastICA.html',
    sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/decomposition/plot_ica_vs_pca.html',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'incremental-pca',
    category: 'unsup',
    subcategory: 'dim-reduction',
    title: '증분 주성분분석 (Incremental PCA)',
    subtitle: '전체 데이터를 한 번에 메모리에 올리지 않고 미니배치 단위로 순차 갱신하며 주성분을 구하는 PCA',
    overview: `<p>일반 PCA는 전체 데이터의 공분산 행렬을 한 번에 계산해야 하므로 데이터가 메모리보다 크면 적용이 어렵습니다. Incremental PCA는 데이터를 작은 배치로 나누어 순차적으로 읽어들이면서 주성분 추정치를 점진적으로 갱신하는 <code>partial_fit</code> 방식을 지원해, 메모리 제약이 있거나 온라인으로 데이터가 들어오는 상황에서도 PCA를 적용할 수 있게 합니다.</p>`,
    formula: ``,
    features: `<p><strong>장점</strong> — 전체 데이터를 메모리에 올릴 필요가 없어 대용량·스트리밍 데이터에도 PCA를 적용할 수 있습니다.</p><p><strong>단점</strong> — 배치 크기 선택에 따라 근사 정확도가 달라지고, 배치 순서에 따라 결과가 약간씩 달라질 수 있습니다.</p>`,
    applications: `<p>메모리에 들어가지 않는 대규모 이미지·센서 데이터셋의 차원 축소, 온라인 학습 파이프라인의 전처리 단계에 사용됩니다. scikit-learn의 <code>IncrementalPCA</code> 클래스로 제공됩니다.</p>`,
    sklearnFunction: 'IncrementalPCA',
    sklearnGuideURL: 'https://scikit-learn.org/stable/modules/decomposition.html#incremental-pca',
    sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.IncrementalPCA.html',
    sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/decomposition/plot_incremental_pca.html',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'k-svd',
    category: 'unsup',
    subcategory: 'dim-reduction',
    title: 'K-SVD',
    subtitle: 'K-평균의 코드북 갱신 원리를 특이값분해로 확장해 과완전 사전을 학습하는 대표적 사전 학습 알고리즘',
    overview: `<p>Aharon, Elad, Bruckstein이 2006년에 제안한 알고리즘으로, 희소 부호화(예: OMP)로 각 신호의 계수를 구하는 단계와, 사전의 각 원자를 하나씩 갱신하는 단계를 번갈아 반복합니다. 원자 갱신 시에는 해당 원자를 사용하는 모든 신호의 잔차 행렬에 대해 랭크-1 SVD를 적용해 원자와 그 계수를 동시에 최적화하며, 이 방식이 K-평균의 클러스터 중심 갱신을 일반화한 것과 유사해 이름이 붙었습니다.</p>`,
    formula: `min&#8337;,&#7615; ||Y &#8722; DX||&#8319;&#178;  s.t. &#8704;i, ||x&#7522;||&#8320; &#8804; T&#8320;  (원자 갱신: 잔차 행렬 E&#8342;의 랭크-1 SVD 근사)`,
    features: `<p><strong>장점</strong> — 사전 학습 정확도가 높아 이미지 복원·압축 품질이 우수하고, 이론적 기반(SVD)이 명확합니다.</p><p><strong>단점</strong> — 반복마다 SVD를 계산해야 해 계산 비용이 크고, 대규모 데이터·고차원 신호에는 확장성이 떨어집니다.</p>`,
    applications: `<p>이미지 잡음 제거(K-SVD 기반 디노이징), 영상 초해상도, 압축 센싱의 사전 학습 등에 사용됩니다. scikit-learn에는 K-SVD가 직접 구현되어 있지 않으며(<code>DictionaryLearning</code>은 좌표 하강법 기반), 원 저자들이 공개한 MATLAB 코드와 커뮤니티의 Python 구현체(예: ksvd 패키지)를 통해 사용됩니다.</p>`,
    sklearnFunction: '',
    sklearnGuideURL: '',
    sklearnAPIURL: '',
    sklearnExampleURL: '',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'lsa',
    category: 'unsup',
    subcategory: 'dim-reduction',
    title: '잠재 의미 분석 (LSA, Latent Semantic Analysis)',
    subtitle: '단어-문서 행렬을 절단 특이값분해(Truncated SVD)로 압축해 잠재적 의미 구조를 드러내는 텍스트 분석 기법',
    overview: `<p>문서 집합을 단어-문서 빈도(TF-IDF) 행렬로 표현한 뒤, 이 행렬에 절단 특이값분해를 적용해 소수의 잠재 의미 차원(토픽)으로 압축합니다. 표면적으로 다른 단어를 쓰더라도 의미적으로 유사한 문서·단어가 잠재 공간에서 가깝게 위치하게 되어, 동의어 문제를 완화하고 문서 유사도 계산·검색 성능을 개선합니다.</p>`,
    formula: `A &#8776; U&#8342;&#931;&#8342;V&#8342;&#7488;  (A: 단어-문서 행렬, 상위 k개 특이값/벡터만 사용)`,
    features: `<p><strong>장점</strong> — 동의어·다의어로 인한 어휘 불일치 문제를 완화하고, 문서·단어를 같은 잠재 공간에 표현해 유사도 계산이 쉬워집니다.</p><p><strong>단점</strong> — 음수 값을 포함할 수 있어 "토픽"의 해석이 명확하지 않고, 잠재 차원 수(k) 선택에 결과가 민감합니다.</p>`,
    applications: `<p>문서 검색·정보 검색의 질의-문서 매칭, 텍스트 군집화 전처리, 추천 시스템의 텍스트 특징 압축 등에 사용됩니다. scikit-learn에서는 <code>TruncatedSVD</code> 클래스가 LSA 구현체로 안내되어 있으며, 텍스트 문서 군집화 예제에서 활용됩니다.</p>`,
    sklearnFunction: 'TruncatedSVD',
    sklearnGuideURL: 'https://scikit-learn.org/stable/modules/decomposition.html#truncated-singular-value-decomposition-and-latent-semantic-analysis',
    sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html',
    sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/applications/plot_topics_extraction_with_nmf_lda.html',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'nmf',
    category: 'unsup',
    subcategory: 'dim-reduction',
    title: '비음수 행렬 분해 (NMF, Non-negative Matrix Factorization)',
    subtitle: '음수를 허용하지 않는 두 저차원 행렬의 곱으로 원본 데이터를 근사하는 파트 기반(part-based) 분해 기법',
    overview: `<p>원본 데이터 행렬 X의 모든 원소가 0 이상이라는 제약(예: 픽셀 강도, 단어 빈도, 유전자 발현량)을 활용해, 역시 음수가 없는 두 행렬 W(기저)와 H(계수)의 곱으로 X를 근사합니다. 뺄셈 없이 덧셈적으로만 성분이 결합되므로 PCA와 달리 "부분들의 합"으로 해석 가능한 파트 기반 표현을 얻는 경우가 많습니다.</p>`,
    formula: `min&#8407;,&#8397;&#8805;&#8320; ||X &#8722; WH||&#8319;&#178;  (Frobenius norm 또는 KL divergence 목적함수, W&#8805;0, H&#8805;0)`,
    features: `<p><strong>장점</strong> — 음수가 없는 파트 기반 표현이라 해석이 직관적이고, 토픽 모델링·이미지 부분 분해에 효과적입니다.</p><p><strong>단점</strong> — 목적함수가 볼록(convex)하지 않아 초기값에 따라 다른 국소해로 수렴하고, 성분 개수를 미리 정해야 합니다.</p>`,
    applications: `<p>텍스트 토픽 모델링, 얼굴 이미지의 부분(눈·코·입) 분해, 추천 시스템의 협업 필터링(행렬 완성) 등에 사용됩니다. scikit-learn의 <code>NMF</code>/<code>MiniBatchNMF</code> 클래스로 제공되며, KL divergence를 쓰는 NMF는 pLSA와 수학적으로 동치임이 알려져 있습니다.</p>`,
    sklearnFunction: 'NMF',
    sklearnGuideURL: 'https://scikit-learn.org/stable/modules/decomposition.html#non-negative-matrix-factorization-nmf-or-nnmf',
    sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.NMF.html',
    sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/applications/plot_topics_extraction_with_nmf_lda.html',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  },
  {
    id: 'online-dictionary-learning',
    category: 'unsup',
    subcategory: 'dim-reduction',
    title: '온라인 사전 학습 (Online Dictionary Learning)',
    subtitle: '데이터를 미니배치·스트림 형태로 순차 처리하며 사전을 확률적으로 갱신하는 대규모 사전 학습 기법',
    overview: `<p>Mairal, Bach, Ponce, Sapiro가 2009년에 제안한 방법으로, 전체 데이터에 대한 기대 손실을 확률적 근사(stochastic approximation)로 최소화합니다. 한 번에 하나 또는 소수의 샘플(미니배치)만 보고 사전을 조금씩 갱신해 나가므로, 전체 데이터를 여러 번 반복해서 봐야 하는 배치 사전 학습보다 훨씬 큰 데이터셋과 스트리밍 상황에 적용할 수 있습니다.</p>`,
    formula: `min&#8337; E&#8416;[ min&#8341; (1/2)||x &#8722; D&#945;||&#178; + &#955;||&#945;||&#8321; ]  (확률적 근사로 온라인 최적화)`,
    features: `<p><strong>장점</strong> — 대용량·스트리밍 데이터에서도 사전 학습이 가능하고, 배치 방식보다 수렴이 빠른 경우가 많습니다.</p><p><strong>단점</strong> — 미니배치 크기와 학습률(감쇠) 설정에 결과가 민감하고, 배치 방식만큼 안정적으로 전역 최적해에 가깝게 수렴한다는 보장은 약합니다.</p>`,
    applications: `<p>대용량 이미지 패치 잡음 제거, 실시간으로 유입되는 신호의 사전 학습 등에 사용됩니다. scikit-learn의 <code>MiniBatchDictionaryLearning</code> 클래스가 이 온라인 사전 학습 알고리즘의 구현체입니다.</p>`,
    sklearnFunction: 'MiniBatchDictionaryLearning',
    sklearnGuideURL: 'https://scikit-learn.org/stable/modules/decomposition.html#dictionary-learning',
    sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.MiniBatchDictionaryLearning.html',
    sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/decomposition/plot_image_denoising.html',
    huggingfaceURL: '',
    spaceURL: '',
    papersWithCodeURL: ''
  }
];
