/* ── AI알고리즘 교과서 데이터 : [2] 지도학습 (List3.md 기준) ── */
/* content-2.js : algorithms.js와 별도 파일 — 병합은 별도 단계에서 진행 */

const CONTENT_2 = [

/* ========================================================= */
/* [2.1.1] 선형 회귀 — 경사하강 최적화 기법 (12) */
/* ========================================================= */
{
  id: 'adam-optimizer',
  category: 'sup',
  subcategory: 'regression',
  title: 'Adam(Adaptive Moment estimation) : 아담 옵티마이저',
  subtitle: '1차·2차 모멘트 추정을 결합해 파라미터별 학습률을 자동 조정하는 경사하강 최적화 기법',
  overview: `<p>그래디언트의 지수이동평균(1차 모멘트, 모멘텀 역할)과 그래디언트 제곱의 지수이동평균(2차 모멘트, 학습률 스케일링 역할)을 동시에 추정하여 파라미터마다 다른 학습률을 적응적으로 부여합니다. 모멘텀과 RMSProp의 장점을 결합한 형태로, 초기값 편향을 보정하는 bias-correction 항을 포함합니다.</p>`,
  formula: `m&#7613; = &#946;&#8321;m&#7613;&#8331;&#8321; + (1&#8722;&#946;&#8321;)g&#7613;,&nbsp;&nbsp; v&#7613; = &#946;&#8322;v&#7613;&#8331;&#8321; + (1&#8722;&#946;&#8322;)g&#7613;&#178;,&nbsp;&nbsp; &#952;&#7613;&#8330;&#8321; = &#952;&#7613; &#8722; &#951;&#183;m&#770;&#7613;/(&#8730;v&#770;&#7613;+&#949;)`,
  features: `<p><strong>장점</strong> — 학습률을 별도로 세밀히 튜닝하지 않아도 빠르고 안정적으로 수렴하며, 희소 그래디언트나 잡음이 많은 목적함수에서도 강건합니다.</p><p><strong>단점</strong> — 이미지 분류 등 일부 과제에서 SGD+모멘텀보다 일반화 성능이 떨어질 수 있고, &#946;&#8321;·&#946;&#8322;·&#949; 하이퍼파라미터에 따라 수렴 안정성이 달라집니다.</p>`,
  applications: `<p>MLP·CNN·RNN·Transformer 등 딥러닝 모델 학습의 사실상 표준 옵티마이저로 PyTorch·TensorFlow에 기본 내장되어 있습니다. scikit-learn에서는 <code>MLPClassifier</code>/<code>MLPRegressor</code>의 <code>solver='adam'</code> 옵션으로 사용할 수 있습니다.</p>`,
  sklearnFunction: "MLPClassifier / MLPRegressor (solver='adam')",
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/neural_networks_supervised.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPRegressor.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/neural_networks/plot_mlp_training_curves.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'adamw-optimizer',
  category: 'sup',
  subcategory: 'regression',
  title: 'AdamW(Adam with decoupled Weight decay) : 아담W 옵티마이저',
  subtitle: 'L2 정규화 항을 그래디언트 업데이트에서 분리해 가중치 감쇠를 직접 적용하는 Adam의 개선판',
  overview: `<p>기존 Adam은 L2 정규화를 손실함수에 더해 그래디언트에 포함시키는데, 이 경우 적응적 학습률 스케일링과 정규화가 뒤섞여 감쇠 효과가 왜곡됩니다. AdamW는 가중치 감쇠(weight decay)를 그래디언트 업데이트와 분리하여 파라미터에 직접 곱해줌으로써 정규화 효과를 일관되게 유지합니다.</p>`,
  formula: `&#952;&#7613;&#8330;&#8321; = &#952;&#7613; &#8722; &#951;&#183;(m&#770;&#7613;/(&#8730;v&#770;&#7613;+&#949;) + &#955;&#952;&#7613;) &nbsp;(&#955; : decoupled weight decay 계수)`,
  features: `<p><strong>장점</strong> — Adam 대비 일반화 성능이 개선되고, 대규모 Transformer 사전학습에서 표준 옵티마이저로 자리잡았습니다.</p><p><strong>단점</strong> — 가중치 감쇠 계수를 별도로 튜닝해야 하며, Adam과 마찬가지로 소규모 데이터에서는 SGD 계열보다 과적합 위험이 있습니다.</p>`,
  applications: `<p>BERT, GPT 계열 등 대규모 언어모델과 비전 Transformer 사전학습의 기본 옵티마이저로 PyTorch <code>torch.optim.AdamW</code>, Hugging Face <code>transformers</code>의 <code>Trainer</code> 기본값으로 널리 쓰입니다. scikit-learn에는 별도 구현이 없어 PyTorch 등 딥러닝 프레임워크를 사용해야 합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: 'https://huggingface.co/docs/transformers/main_classes/optimizer_schedules',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'batch-gradient-descent',
  category: 'sup',
  subcategory: 'regression',
  title: 'Batch Gradient Descent : 배치 경사하강법',
  subtitle: '전체 학습 데이터를 한 번에 사용해 그래디언트를 계산하고 파라미터를 갱신하는 가장 기본적인 경사하강법',
  overview: `<p>매 반복(iteration)마다 전체 학습 데이터셋에 대한 손실함수의 그래디언트를 정확히 계산한 뒤 파라미터를 한 번 갱신합니다. 그래디언트 추정이 정확해 수렴 경로가 안정적이지만, 데이터가 클수록 한 스텝당 연산 비용이 커집니다.</p>`,
  formula: `&#952; = &#952; &#8722; &#951;&#183;&#8711;J(&#952;) &nbsp;,&nbsp; &#8711;J(&#952;) = (1/n)&#8721;&#8290;&#7522;&#8321;&#7497;&#8711;J&#7522;(&#952;)`,
  features: `<p><strong>장점</strong> — 그래디언트 추정 잡음이 없어 수렴 경로가 매끄럽고 안정적입니다.</p><p><strong>단점</strong> — 매 스텝마다 전체 데이터를 순회해야 해 대용량 데이터에서는 느리고 메모리 부담이 크며, 지역 최소값에 갇히기 쉽습니다.</p>`,
  applications: `<p>데이터 규모가 작은 통계 모델링·교육용 예제에서 최적화 개념 설명에 주로 사용되며, scikit-learn의 <code>LinearRegression</code>은 실제로는 경사하강법 대신 최소제곱 closed-form(SVD) 해를 사용합니다. 실무 대용량 학습에서는 미니배치·확률적 경사하강법으로 대체됩니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'lbfgs-optimizer',
  category: 'sup',
  subcategory: 'regression',
  title: 'L-BFGS(Limited-memory BFGS) : 제한 메모리 BFGS',
  subtitle: '2차 도함수(헤시안)를 근사해 적은 메모리로 빠르게 수렴하는 준뉴턴(quasi-Newton) 최적화 기법',
  overview: `<p>BFGS 알고리즘의 헤시안 역행렬 근사를 전체 저장하지 않고 최근 m개의 그래디언트·파라미터 변화량만 저장해 근사하는 방식입니다. 곡률 정보를 활용하기 때문에 1차 미분만 쓰는 경사하강법보다 적은 반복 횟수로 수렴합니다.</p>`,
  formula: `&#952;&#7613;&#8330;&#8321; = &#952;&#7613; &#8722; H&#7613;&#8290;&#8711;J(&#952;&#7613;) &nbsp;(H&#7613; : 제한된 이력으로 근사한 역헤시안)`,
  features: `<p><strong>장점</strong> — 소규모·중간 규모 데이터에서 적은 반복으로 빠르게 수렴하고 학습률 튜닝 부담이 적습니다.</p><p><strong>단점</strong> — 미니배치 확률적 학습에는 적합하지 않고 배치 전체 그래디언트가 필요해 대규모 데이터·딥러닝에는 잘 쓰이지 않습니다.</p>`,
  applications: `<p>scikit-learn의 <code>LogisticRegression</code>·<code>MLPClassifier</code>/<code>MLPRegressor</code>에서 <code>solver='lbfgs'</code>로 기본 제공되며, 중소규모 표 형태 데이터의 로지스틱 회귀·신경망 학습에 널리 쓰입니다.</p>`,
  sklearnFunction: "LogisticRegression / MLPClassifier (solver='lbfgs')",
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'learning-rate-decay',
  category: 'sup',
  subcategory: 'regression',
  title: 'Learning Rate Decay : 학습률 감소',
  subtitle: '학습이 진행됨에 따라 학습률을 점진적으로 낮춰 수렴 안정성을 높이는 스케줄링 기법',
  overview: `<p>학습 초반에는 큰 학습률로 빠르게 손실을 줄이고, 후반에는 학습률을 줄여 최적점 주변에서 진동하지 않고 세밀하게 수렴하도록 유도합니다. 스텝 감소, 지수 감소, 역제곱근 감소(inverse scaling) 등 다양한 스케줄이 있습니다.</p>`,
  formula: `&#951;&#7613; = &#951;&#8320; / (1 + k&#183;t) &nbsp;(step decay 예시, t: 반복 횟수, k: 감소율)`,
  features: `<p><strong>장점</strong> — 학습 후반 진동을 줄여 더 정밀한 최적해에 도달하도록 돕습니다.</p><p><strong>단점</strong> — 감소 일정(스케줄)을 잘못 설정하면 너무 빨리 학습률이 작아져 조기 수렴·성능 저하가 발생할 수 있습니다.</p>`,
  applications: `<p>scikit-learn <code>SGDRegressor</code>/<code>SGDClassifier</code>의 <code>learning_rate='invscaling'</code>/<code>'adaptive'</code> 옵션으로 제공되며, 딥러닝에서는 StepLR·CosineAnnealing 등 다양한 스케줄러로 구현되어 모델 학습 전반에 사용됩니다.</p>`,
  sklearnFunction: "SGDRegressor / SGDClassifier (learning_rate='invscaling')",
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/sgd.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'lookahead-optimizer',
  category: 'sup',
  subcategory: 'regression',
  title: 'Lookahead : 루카헤드',
  subtitle: '내부(fast) 옵티마이저가 k스텝 앞서 탐색한 뒤 외부(slow) 가중치를 그 방향으로 보간하는 메타 옵티마이저',
  overview: `<p>Adam·SGD 같은 기본(내부) 옵티마이저가 k번의 스텝을 먼저 진행해 "빠른 가중치"를 만들면, 외부 가중치를 빠른 가중치 방향으로 선형 보간해 이동시킵니다. 이 과정을 반복하면서 분산을 줄이고 더 안정적인 최소값을 찾도록 돕습니다.</p>`,
  formula: `&#966;&#7613;&#8330;&#8321; = &#966;&#7613; + &#945;&#183;(&#952;&#7613;,&#8342; &#8722; &#966;&#7613;) &nbsp;(&#966;: slow weights, &#952;: k스텝 후 fast weights, &#945;: 보간 계수)`,
  features: `<p><strong>장점</strong> — 내부 옵티마이저의 분산을 줄여 학습 안정성과 최종 성능을 개선하며, 대부분의 기존 옵티마이저 위에 손쉽게 결합할 수 있습니다.</p><p><strong>단점</strong> — 추가 하이퍼파라미터(k, &#945;)가 필요하고 스텝당 연산량이 늘어나며, scikit-learn 등 전통적 라이브러리에는 내장되어 있지 않습니다.</p>`,
  applications: `<p>이미지 분류·번역 등 대규모 딥러닝 학습에서 Adam과 결합한 "Ranger" 옵티마이저 형태로 PyTorch 커뮤니티 구현체를 통해 주로 사용됩니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'mini-batch-gradient-descent',
  category: 'sup',
  subcategory: 'regression',
  title: 'Mini-batch Gradient Descent : 미니배치 경사하강법',
  subtitle: '전체 데이터를 작은 배치 단위로 나누어 그래디언트를 계산·갱신하는 실무 표준 경사하강법',
  overview: `<p>배치 경사하강법(전체 데이터)과 확률적 경사하강법(샘플 1개)의 절충안으로, 수십~수천 개 단위의 미니배치마다 그래디언트를 계산해 파라미터를 갱신합니다. GPU 병렬 연산과 잘 맞아 딥러닝 학습의 사실상 표준 방식입니다.</p>`,
  formula: `&#952; = &#952; &#8722; &#951;&#183;(1/|B|)&#8721;&#8290;&#7522;&#8712;B&#8711;J&#7522;(&#952;) &nbsp;(B: 미니배치)`,
  features: `<p><strong>장점</strong> — 배치 경사하강법보다 메모리 효율적이고 확률적 경사하강법보다 그래디언트 추정이 안정적이며 GPU 병렬화에 유리합니다.</p><p><strong>단점</strong> — 배치 크기라는 추가 하이퍼파라미터가 필요하며 너무 크면 일반화 성능이, 너무 작으면 학습 안정성이 떨어질 수 있습니다.</p>`,
  applications: `<p>scikit-learn의 <code>SGDRegressor</code>/<code>SGDClassifier</code>의 <code>partial_fit()</code>과 <code>MiniBatchKMeans</code> 등에서 개념적으로 활용되며, 딥러닝 프레임워크의 <code>DataLoader</code> 배치 학습이 대표적 구현 사례입니다.</p>`,
  sklearnFunction: 'SGDRegressor / SGDClassifier (partial_fit)',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/sgd.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'momentum-gradient-descent',
  category: 'sup',
  subcategory: 'regression',
  title: 'Momentum Gradient Descent : 모멘텀 경사하강법',
  subtitle: '이전 그래디언트의 방향을 관성처럼 누적해 진동을 줄이고 수렴을 가속하는 경사하강법',
  overview: `<p>현재 그래디언트뿐 아니라 이전 갱신 방향을 일정 비율로 누적한 속도(velocity) 항을 함께 사용합니다. 골짜기 모양의 손실 지형에서 좌우 진동은 상쇄되고 일관된 방향으로는 가속되어 SGD보다 빠르고 안정적으로 수렴합니다.</p>`,
  formula: `v&#7613; = &#947;v&#7613;&#8331;&#8321; + &#951;&#8711;J(&#952;&#7613;),&nbsp;&nbsp; &#952;&#7613;&#8330;&#8321; = &#952;&#7613; &#8722; v&#7613; &nbsp;(&#947; : 모멘텀 계수, 보통 0.9)`,
  features: `<p><strong>장점</strong> — 안장점·좁은 골짜기에서 진동을 줄이고 수렴 속도를 높입니다.</p><p><strong>단점</strong> — 모멘텀 계수가 너무 크면 최적점을 지나치는 오버슈팅이 발생할 수 있습니다.</p>`,
  applications: `<p>scikit-learn <code>MLPClassifier</code>/<code>MLPRegressor</code>의 <code>solver='sgd', momentum=0.9</code> 옵션으로 제공되며, 딥러닝 프레임워크의 SGD 옵티마이저 기본 구성요소로 널리 쓰입니다.</p>`,
  sklearnFunction: "MLPClassifier / MLPRegressor (solver='sgd', momentum)",
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/neural_networks_supervised.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPRegressor.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'nesterov-accelerated-gradient',
  category: 'sup',
  subcategory: 'regression',
  title: 'NAG(Nesterov Accelerated Gradient) : 네스테로프 가속 경사하강법',
  subtitle: '모멘텀으로 먼저 이동한 지점에서 그래디언트를 계산해 방향 보정력을 높인 가속 경사하강법',
  overview: `<p>일반 모멘텀이 현재 위치의 그래디언트를 사용하는 것과 달리, 모멘텀 방향으로 미리 한 걸음 내다본(lookahead) 지점에서 그래디언트를 계산합니다. 이 "선견지명" 덕분에 최적점에 가까워질 때 더 빠르게 감속해 오버슈팅을 줄입니다.</p>`,
  formula: `v&#7613; = &#947;v&#7613;&#8331;&#8321; + &#951;&#8711;J(&#952;&#7613; &#8722; &#947;v&#7613;&#8331;&#8321;),&nbsp;&nbsp; &#952;&#7613;&#8330;&#8321; = &#952;&#7613; &#8722; v&#7613;`,
  features: `<p><strong>장점</strong> — 일반 모멘텀보다 이론적 수렴 속도가 빠르고(볼록 함수 기준 O(1/t&#178;)), 오버슈팅이 적습니다.</p><p><strong>단점</strong> — 비볼록 손실 지형에서는 이론적 이점이 항상 보장되지 않으며 구현이 모멘텀보다 다소 복잡합니다.</p>`,
  applications: `<p>scikit-learn <code>MLPClassifier</code>/<code>MLPRegressor</code>의 <code>solver='sgd', nesterovs_momentum=True</code> 옵션으로 제공되며, 딥러닝 프레임워크(PyTorch SGD의 <code>nesterov=True</code>)에서도 표준 옵션으로 지원됩니다.</p>`,
  sklearnFunction: "MLPClassifier / MLPRegressor (solver='sgd', nesterovs_momentum=True)",
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/neural_networks_supervised.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPRegressor.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'newtons-method-optimization',
  category: 'sup',
  subcategory: 'regression',
  title: "Newton's Method : 뉴턴 방법",
  subtitle: '2차 도함수(헤시안)를 직접 이용해 곡률 정보를 반영한 최적화 기법',
  overview: `<p>1차 미분(그래디언트)만 사용하는 경사하강법과 달리 손실함수의 2차 미분인 헤시안 행렬의 역행렬을 이용해 파라미터를 갱신합니다. 곡률을 정확히 반영하기 때문에 이차식에 가까운 손실함수에서는 한두 번의 반복만으로도 빠르게 수렴합니다.</p>`,
  formula: `&#952;&#7613;&#8330;&#8321; = &#952;&#7613; &#8722; H&#7613;&#8331;&#185;&#8711;J(&#952;&#7613;) &nbsp;(H: 헤시안 행렬)`,
  features: `<p><strong>장점</strong> — 볼록 함수에서 매우 빠른(2차) 수렴 속도를 보이며 학습률 튜닝 부담이 적습니다.</p><p><strong>단점</strong> — 파라미터 수가 많을수록 헤시안 계산·역행렬 연산 비용(O(n&#179;))이 급격히 커져 고차원 딥러닝에는 부적합합니다.</p>`,
  applications: `<p>scikit-learn <code>LogisticRegression</code>의 <code>solver='newton-cg'</code>/<code>'newton-cholesky'</code> 옵션으로 제공되며, 파라미터 수가 적은 통계 모델·GLM 적합에 주로 사용됩니다.</p>`,
  sklearnFunction: "LogisticRegression (solver='newton-cg' / 'newton-cholesky')",
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'sgd-optimizer',
  category: 'sup',
  subcategory: 'regression',
  title: 'SGD(Stochastic Gradient Descent) : 확률적 경사하강법',
  subtitle: '무작위로 선택한 샘플 1개(또는 소수)마다 그래디언트를 계산해 즉시 갱신하는 경사하강법',
  overview: `<p>전체 데이터의 정확한 그래디언트 대신 매 스텝 무작위 샘플에서 추정한 그래디언트로 파라미터를 갱신합니다. 잡음이 섞인 그래디언트 덕분에 지역 최소값이나 안장점을 벗어나기 쉽고, 스트리밍 데이터의 온라인 학습에도 적합합니다.</p>`,
  formula: `&#952;&#7613;&#8330;&#8321; = &#952;&#7613; &#8722; &#951;&#183;&#8711;J&#7522;(&#952;&#7613;) &nbsp;(i: 무작위 추출된 샘플 인덱스)`,
  features: `<p><strong>장점</strong> — 스텝당 연산이 저렴해 대용량·스트리밍 데이터에 적합하고 지역 최적해 탈출에 유리합니다.</p><p><strong>단점</strong> — 그래디언트 추정 잡음으로 수렴 경로가 불안정하며 학습률·스케줄을 세심히 조정해야 합니다.</p>`,
  applications: `<p>scikit-learn의 <code>SGDRegressor</code>/<code>SGDClassifier</code>가 대표 구현체이며, 대용량 텍스트 분류·온라인 추천 시스템처럼 데이터가 지속적으로 유입되는 환경에서 널리 쓰입니다.</p>`,
  sklearnFunction: 'SGDRegressor / SGDClassifier',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/sgd.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_sgd_separating_hyperplane.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'warmup-schedule',
  category: 'sup',
  subcategory: 'regression',
  title: 'Warm-up : 워밍업',
  subtitle: '학습 초반 학습률을 0에 가깝게 시작해 점진적으로 목표 학습률까지 끌어올리는 스케줄링 기법',
  overview: `<p>학습 초기에 파라미터가 무작위 초기값 상태에서 큰 학습률을 바로 적용하면 그래디언트가 불안정해질 수 있습니다. Warm-up은 처음 몇 스텝(또는 몇 에폭) 동안 학습률을 선형·지수적으로 서서히 증가시켜 학습 초반의 발산을 방지한 뒤, 이후 본 스케줄(감소 등)로 전환합니다.</p>`,
  formula: `&#951;&#7613; = &#951;&#8320;&#183;(t/t&#8290;&#8340;&#8366;&#8340;&#8339;&#8290;&#8354;&#8346;) &nbsp;(0 &#8804; t &#8804; t&#8290;&#8340;&#8366;&#8340;&#8339;&#8290;&#8354;&#8346;, 이후 감소 스케줄로 전환)`,
  features: `<p><strong>장점</strong> — 학습 초반의 불안정한 그래디언트로 인한 발산을 방지하고, 특히 배치 크기가 크거나 Transformer처럼 깊은 모델에서 학습 안정성을 크게 높입니다.</p><p><strong>단점</strong> — 워밍업 스텝 수라는 추가 하이퍼파라미터가 필요하며, scikit-learn 등 전통적 라이브러리에는 내장되어 있지 않습니다.</p>`,
  applications: `<p>BERT·GPT·ViT 등 대규모 Transformer 사전학습의 표준 학습률 스케줄 구성요소로, Hugging Face <code>transformers</code>의 <code>get_linear_schedule_with_warmup</code> 등에서 기본 제공됩니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: 'https://huggingface.co/docs/transformers/main_classes/optimizer_schedules',
  spaceURL: '',
  papersWithCodeURL: ''
},

/* ========================================================= */
/* [2.1.2] 일반화 선형 회귀 (GLM) (13) */
/* ========================================================= */
{
  id: 'bayesian-glm',
  category: 'sup',
  subcategory: 'regression',
  title: 'Bayesian GLM(Generalized Linear Model) : 베이즈 GLM',
  subtitle: '계수에 사전분포를 부여하고 베이즈 추론으로 사후분포를 추정하는 일반화 선형모형',
  overview: `<p>고전적 GLM이 계수의 점추정치 하나만 제공하는 것과 달리, 계수에 사전분포를 두고 데이터를 관측한 뒤의 사후분포 전체를 추정합니다. 예측값뿐 아니라 불확실성(신용구간)을 함께 제공할 수 있어 의사결정에 유용합니다.</p>`,
  formula: `p(&#946;|y,X) &#8733; p(y|X,&#946;)&#183;p(&#946;) &nbsp;(사전분포 p(&#946;)와 우도의 곱에 비례하는 사후분포)`,
  features: `<p><strong>장점</strong> — 파라미터 불확실성을 정량화하고 사전지식을 모델에 반영할 수 있으며 소규모 데이터에서 과적합을 완화합니다.</p><p><strong>단점</strong> — 사후분포 계산에 MCMC·변분추론 등 추가 연산이 필요해 대규모 데이터에서는 계산 비용이 큽니다.</p>`,
  applications: `<p>scikit-learn의 <code>BayesianRidge</code>/<code>ARDRegression</code>은 가우시안 우도에 한정된 베이즈 선형회귀를 제공하며, 이항·포아송 등 일반적인 링크함수를 포함한 완전한 베이즈 GLM은 PyMC·Stan(brms) 같은 확률적 프로그래밍 라이브러리로 구현하는 것이 일반적입니다.</p>`,
  sklearnFunction: 'BayesianRidge / ARDRegression (가우시안 우도 한정)',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#bayesian-regression',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.BayesianRidge.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'binomial-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Binomial Regression : 이항 회귀',
  subtitle: '이항분포를 가정하고 로짓·프로빗 등의 링크함수로 성공 확률을 모델링하는 GLM',
  overview: `<p>반응변수가 특정 시행 횟수 중 성공 횟수(또는 이진값)일 때, 이항분포를 우도로 가정하고 로짓 링크함수를 통해 선형예측자와 성공확률을 연결하는 일반화 선형모형입니다. 이진 분류 문제에서의 로지스틱 회귀는 이항 회귀의 특수한 경우(시행 횟수=1)입니다.</p>`,
  formula: `logit(p) = log(p/(1&#8722;p)) = X&#946; &nbsp;(p: 성공 확률)`,
  features: `<p><strong>장점</strong> — 확률로 해석 가능한 출력을 제공하고 계수의 오즈비 해석이 직관적입니다.</p><p><strong>단점</strong> — 과산포(overdispersion)가 있는 데이터에서는 표준오차가 과소추정될 수 있어 준이항(quasi-binomial) 보정이 필요합니다.</p>`,
  applications: `<p>이진 반응(로지스틱 회귀)은 scikit-learn <code>LogisticRegression</code>으로, 시행 횟수 대비 성공비율 형태의 일반적인 이항 회귀는 statsmodels의 <code>GLM(family=Binomial)</code>으로 적합하는 것이 일반적입니다.</p>`,
  sklearnFunction: 'LogisticRegression (이진 반응의 특수 사례)',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'cox-proportional-hazard-model',
  category: 'sup',
  subcategory: 'regression',
  title: 'Cox Proportional Hazard Model : 콕스 비례위험 모형',
  subtitle: '사건 발생까지의 시간(생존시간)을 공변량으로 설명하는 준모수적 생존분석 회귀모형',
  overview: `<p>기저 위험함수(baseline hazard)의 형태를 특정하지 않고, 공변량이 위험(hazard)에 곱셈적으로 비례하는 영향을 미친다고 가정하는 준모수 모형입니다. 부분우도(partial likelihood)를 최대화해 계수를 추정하며 중도절단(censoring) 데이터를 자연스럽게 다룹니다.</p>`,
  formula: `h(t|X) = h&#8320;(t)&#183;exp(X&#946;) &nbsp;(h&#8320;(t): 기저 위험함수)`,
  features: `<p><strong>장점</strong> — 기저 위험함수의 분포를 가정하지 않아도 되고 중도절단된 생존 데이터를 그대로 활용할 수 있습니다.</p><p><strong>단점</strong> — 위험비가 시간에 따라 일정하다는 비례위험 가정이 깨지면 추정치가 편향될 수 있습니다.</p>`,
  applications: `<p>임상시험의 생존분석(치료군 간 사망·재발 위험 비교), 고객 이탈까지의 시간 예측 등에 사용되며, scikit-learn과 API 호환되는 <code>scikit-survival</code>의 <code>CoxPHSurvivalAnalysis</code>나 R의 <code>survival</code> 패키지, Python <code>lifelines</code> 라이브러리로 적합합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'gam-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'GAM(Generalized Additive Model) : 일반화 가법모형',
  subtitle: '각 설명변수에 개별적인 평활 함수(스플라인)를 적용해 비선형 관계를 유연하게 모델링하는 GLM 확장',
  overview: `<p>선형예측자 X&#946;를 각 변수별 평활함수(smooth function)의 합 &#8721;f&#8320;(x&#8320;)로 대체해, 변수별로 서로 다른 비선형 형태를 허용하면서도 전체 모델의 해석력(변수별 부분효과 시각화)은 유지합니다.</p>`,
  formula: `g(E[y]) = &#946;&#8320; + f&#8321;(x&#8321;) + f&#8322;(x&#8322;) + &#8943; + f&#8342;(x&#8342;) &nbsp;(g: 링크함수, f&#8290;&#7522;: 평활 함수)`,
  features: `<p><strong>장점</strong> — 비선형 관계를 자동으로 포착하면서도 변수별 부분함수를 그려 해석할 수 있어 화이트박스 모델에 가깝습니다.</p><p><strong>단점</strong> — 평활 파라미터(스플라인 자유도) 선택이 필요하고 변수 간 상호작용을 다루려면 별도의 텐서곱 항을 추가해야 합니다.</p>`,
  applications: `<p>보험료율 산정, 의료 위험도 예측, 수요 예측 등 비선형이면서도 해석 가능성이 중요한 분야에서 사용되며, Python <code>pyGAM</code> 라이브러리가 scikit-learn과 유사한 API로 GAM을 제공합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'gamma-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Gamma Regression : 감마 회귀',
  subtitle: '양의 연속값이며 오른쪽으로 긴 꼬리를 갖는 반응변수에 감마분포를 가정하는 GLM',
  overview: `<p>보험 손해액, 대기시간처럼 항상 양수이고 분산이 평균의 제곱에 비례하는 데이터에 적합한 GLM입니다. 로그 링크함수를 사용하면 계수가 반응변수에 대한 곱셈적(percentage) 효과로 해석됩니다.</p>`,
  formula: `log(E[y]) = X&#946; &nbsp;(y &#8764; Gamma(&#956;, &#957;), Var(y) &#8733; &#956;&#178;)`,
  features: `<p><strong>장점</strong> — 항상 양수인 오른쪽 비대칭 데이터를 자연스럽게 모델링하고 이분산성을 반영합니다.</p><p><strong>단점</strong> — 반응변수에 0이나 음수가 있으면 사용할 수 없어 사전 변수 처리가 필요합니다.</p>`,
  applications: `<p>보험 청구액 예측, 의료비 예측 등에 활용되며 scikit-learn의 <code>GammaRegressor</code>(내부적으로 <code>TweedieRegressor(power=2)</code>와 동일)로 바로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'GammaRegressor',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#generalized-linear-models',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.GammaRegressor.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_tweedie_regression_insurance_claims.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'hurdle-model',
  category: 'sup',
  subcategory: 'regression',
  title: 'Hurdle Model : 허들 모형',
  subtitle: '0 발생 여부와 양수 발생 건수를 두 단계로 분리해 모델링하는 카운트 데이터 회귀모형',
  overview: `<p>1단계에서 이진모형(로짓·프로빗)으로 "0이냐 양수냐"를 모델링하고, 2단계에서 0을 넘긴(hurdle을 통과한) 관측치에 한해 절단된 포아송·음이항 분포로 양의 카운트를 모델링합니다. 두 과정이 서로 다른 메커니즘일 수 있다는 가정 하에 유연하게 적합합니다.</p>`,
  formula: `P(y=0) = 1&#8722;&#960;,&nbsp;&nbsp; P(y=k|y&gt;0) = &#960;&#183;f(k)/(1&#8722;f(0)) &nbsp;(k&#8805;1, f: 카운트분포)`,
  features: `<p><strong>장점</strong> — 0의 발생 과정과 양의 값 발생 과정을 별도로 설명해 영과잉·영과소 데이터 모두에 유연하게 대응합니다.</p><p><strong>단점</strong> — 두 개의 하위모형을 각각 적합·해석해야 해 모델 복잡도와 파라미터 수가 늘어납니다.</p>`,
  applications: `<p>병원 방문 횟수, 보험 청구 건수처럼 0이 특별한 의미를 갖는 카운트 데이터 분석에 사용되며, Python statsmodels의 <code>HurdleCountModel</code>(Poisson/음이항 혼합)로 적합할 수 있습니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'inverse-gaussian-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Inverse Gaussian Regression : 역가우시안 회귀',
  subtitle: '감마분포보다 더 꼬리가 두꺼운 양의 연속값 데이터에 역가우시안 분포를 가정하는 GLM',
  overview: `<p>분산이 평균의 세제곱에 비례하는(Var(y)&#8733;&#956;&#179;) 극단적으로 오른쪽 비대칭인 양의 연속 데이터에 사용하는 GLM으로, Tweedie 분포族에서 power=3에 해당합니다.</p>`,
  formula: `log(E[y]) = X&#946; &nbsp;(y &#8764; InverseGaussian(&#956;), Var(y) &#8733; &#956;&#179;)`,
  features: `<p><strong>장점</strong> — 감마분포보다 꼬리가 두꺼운 극단값이 많은 데이터를 감마 회귀보다 잘 적합합니다.</p><p><strong>단점</strong> — 해석이 직관적이지 않고 실무 데이터에서 감마·포아송보다 사용 빈도가 낮습니다.</p>`,
  applications: `<p>공정 소요시간, 특정 보험 손해액 분포처럼 극단값이 두드러진 데이터 모델링에 활용되며, scikit-learn의 <code>TweedieRegressor(power=3)</code>로 근사적으로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'TweedieRegressor (power=3)',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#generalized-linear-models',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.TweedieRegressor.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'negative-binomial-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Negative Binomial Regression : 음이항 회귀',
  subtitle: '포아송 회귀의 등분산 가정(평균=분산)이 깨진 과산포 카운트 데이터를 위한 GLM',
  overview: `<p>포아송분포는 평균과 분산이 같다고 가정하지만 실제 카운트 데이터는 분산이 평균보다 큰 과산포(overdispersion)를 보이는 경우가 많습니다. 음이항분포는 포아송-감마 혼합으로 이러한 과산포를 추가 파라미터로 흡수합니다.</p>`,
  formula: `Var(y) = &#956; + &#945;&#956;&#178; &nbsp;(&#945;: 과산포 파라미터, &#945;&#8594;0이면 포아송에 수렴)`,
  features: `<p><strong>장점</strong> — 포아송 회귀보다 과산포된 실제 카운트 데이터에 잘 맞고 표준오차 과소추정 문제를 완화합니다.</p><p><strong>단점</strong> — 과산포 파라미터를 추가로 추정해야 하며 scikit-learn에는 내장 구현이 없습니다.</p>`,
  applications: `<p>사고 건수, 질병 발생 건수 등 과산포가 흔한 역학·보험 데이터 분석에 널리 쓰이며, Python <code>statsmodels</code>의 <code>NegativeBinomial</code>/<code>GLM(family=NegativeBinomial)</code>로 적합합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'poisson-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Poisson Regression : 포아송 회귀',
  subtitle: '단위 시간·공간당 발생 횟수(카운트 데이터)를 모델링하는 대표적인 GLM',
  overview: `<p>반응변수가 음이 아닌 정수 카운트일 때 포아송분포를 우도로 가정하고 로그 링크함수로 선형예측자와 평균 발생률을 연결합니다. 평균과 분산이 같다는(등산포) 포아송분포의 성질을 그대로 따릅니다.</p>`,
  formula: `log(&#955;) = X&#946; &nbsp;(y &#8764; Poisson(&#955;), &#955;: 평균 발생률)`,
  features: `<p><strong>장점</strong> — 계수를 발생률에 대한 상대적(곱셈적) 효과로 직관적으로 해석할 수 있습니다.</p><p><strong>단점</strong> — 실제 데이터의 분산이 평균보다 큰 과산포 상황에서는 표준오차가 과소추정되어 음이항 회귀로 대체해야 합니다.</p>`,
  applications: `<p>보험 청구 건수, 웹사이트 방문 건수, 콜센터 문의 건수 예측 등에 사용되며 scikit-learn의 <code>PoissonRegressor</code>로 바로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'PoissonRegressor',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#generalized-linear-models',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.PoissonRegressor.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_poisson_regression_non_normal_loss.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'quasi-poisson-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Quasi-Poisson Regression : 준포아송 회귀',
  subtitle: '분포 형태를 완전히 특정하지 않고 분산이 평균에 비례한다고만 가정해 과산포를 보정하는 회귀',
  overview: `<p>포아송 회귀와 계수 추정 방식(준우도)은 같지만, 분산을 평균의 상수배(&#966;&#956;)로 허용하는 분산팽창계수 &#966;를 추가로 추정해 과산포된 카운트 데이터에서도 표준오차를 올바르게 보정합니다.</p>`,
  formula: `Var(y) = &#966;&#183;&#956; &nbsp;(&#966;: 분산팽창계수, &#966;&gt;1이면 과산포)`,
  features: `<p><strong>장점</strong> — 완전한 확률분포를 가정하지 않고도 과산포를 보정할 수 있어 음이항 회귀보다 가정이 가볍습니다.</p><p><strong>단점</strong> — 완전한 우도함수가 없어 AIC 등 우도 기반 모델 비교 지표를 직접 사용하기 어렵습니다.</p>`,
  applications: `<p>과산포가 의심되지만 음이항 분포의 형태 가정까지는 부담스러운 생태·역학 카운트 데이터 분석에 사용되며, R의 <code>glm(family=quasipoisson)</code>이나 Python statsmodels의 강건 표준오차(robust covariance) 옵션으로 구현합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'regularized-glm',
  category: 'sup',
  subcategory: 'regression',
  title: 'Regularized GLM(Generalized Linear Model) : 정규화 GLM',
  subtitle: '포아송·감마·트위디 등 GLM의 로그우도에 L1/L2 벌점을 더해 과적합을 억제하는 방식',
  overview: `<p>표준 GLM의 음의 로그우도 손실에 릿지(L2)나 라쏘(L1) 벌점을 추가하여, 설명변수가 많거나 다중공선성이 있는 상황에서도 안정적인 계수 추정을 얻습니다. 링크함수·분포 가정은 유지한 채 정규화 항만 결합한 형태입니다.</p>`,
  formula: `min&#8342; &#8722;logL(&#946;) + &#945;&#8290;(&#961;||&#946;||&#8321; + (1&#8722;&#961;)/2&#183;||&#946;||&#178;&#8322;) &nbsp;(&#945;: 정규화 강도, &#961;: L1 비율)`,
  features: `<p><strong>장점</strong> — 변수가 많은 GLM에서 과적합을 방지하고 계수를 안정화하며, L1 비율을 조정해 변수 선택 효과도 얻을 수 있습니다.</p><p><strong>단점</strong> — 정규화 강도 &#945;와 혼합비율을 교차검증으로 튜닝해야 해 추가 계산 비용이 발생합니다.</p>`,
  applications: `<p>scikit-learn의 <code>PoissonRegressor</code>·<code>GammaRegressor</code>·<code>TweedieRegressor</code>는 모두 <code>alpha</code> 파라미터로 L2 정규화를 기본 지원하며, 고차원 보험·의료 카운트 데이터의 GLM 적합에 사용됩니다.</p>`,
  sklearnFunction: 'PoissonRegressor / GammaRegressor / TweedieRegressor (alpha)',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#generalized-linear-models',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.TweedieRegressor.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'tweedie-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Tweedie Regression : 트위디 회귀',
  subtitle: '포아송·감마·역가우시안을 power 파라미터 하나로 아우르는 지수분산족 GLM',
  overview: `<p>Tweedie 분포는 power 파라미터 p에 따라 정규분포(p=0), 포아송(p=1), 복합포아송-감마(1&lt;p&lt;2), 감마(p=2), 역가우시안(p=3)을 모두 포괄하는 지수분산족입니다. 특히 1&lt;p&lt;2 구간은 0이 많으면서 양수는 연속적인 보험 손해액처럼 "0이 있는 양의 연속값"을 하나의 분포로 자연스럽게 표현할 수 있어 실무에서 유용합니다.</p>`,
  formula: `Var(y) = &#966;&#183;&#956;&#7477; &nbsp;(p: power 파라미터, &#966;: 분산 파라미터)`,
  features: `<p><strong>장점</strong> — power 하나로 다양한 분포 형태를 아우르며 0과 양의 연속값이 섞인 데이터(순보험료 등)를 별도 허들모형 없이 한 번에 모델링할 수 있습니다.</p><p><strong>단점</strong> — power 파라미터를 데이터로부터 별도로 추정하거나 교차검증으로 탐색해야 합니다.</p>`,
  applications: `<p>손해보험의 순보험료(청구 건수&#215;청구액) 예측이 대표 사례이며, scikit-learn의 <code>TweedieRegressor</code>로 <code>power</code> 값을 지정해 바로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'TweedieRegressor',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#generalized-linear-models',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.TweedieRegressor.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_tweedie_regression_insurance_claims.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'zero-inflated-model',
  category: 'sup',
  subcategory: 'regression',
  title: 'Zero-Inflated Model : 영과잉 모형',
  subtitle: '표준 카운트분포가 설명하는 것보다 0이 훨씬 많은 데이터를 위한 혼합 카운트 회귀모형',
  overview: `<p>관측된 0이 "구조적으로 절대 발생하지 않는 0"과 "카운트분포상 우연히 관측된 0"의 혼합에서 나온다고 가정합니다. 이진모형으로 구조적 0의 확률을 추정하고, 나머지는 포아송·음이항 등 카운트분포로 모델링하는 혼합모형입니다.</p>`,
  formula: `P(y=0) = &#960; + (1&#8722;&#960;)f(0),&nbsp;&nbsp; P(y=k) = (1&#8722;&#960;)f(k) &nbsp;(k&#8805;1, &#960;: 구조적 0 비율)`,
  features: `<p><strong>장점</strong> — 허들모형과 달리 0이 카운트분포에서도 자연 발생할 수 있음을 허용해 더 유연하며, 구조적 0 비율을 별도로 해석할 수 있습니다.</p><p><strong>단점</strong> — 허들모형보다 파라미터 식별이 어려울 수 있고 두 성분(0 여부, 카운트) 간 혼동으로 해석이 복잡해질 수 있습니다.</p>`,
  applications: `<p>제조 결함 건수, 특정 질병의 발병 건수처럼 절대다수가 0인 카운트 데이터에 사용되며, Python statsmodels의 <code>ZeroInflatedPoisson</code>/<code>ZeroInflatedNegativeBinomialP</code>로 적합합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},

/* ========================================================= */
/* [2.1.3] 다중 선형 회귀 (4) */
/* ========================================================= */
{
  id: 'hierarchical-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Hierarchical Regression : 위계적 회귀',
  subtitle: '설명변수를 이론적 순서에 따라 여러 블록으로 나누어 단계적으로 투입하며 설명력 증가분을 검정하는 회귀 분석법',
  overview: `<p>통제변수 블록을 먼저 투입해 기저 모형을 만들고, 이후 관심 있는 예측변수 블록을 순서대로 추가하며 각 단계에서 R&#178;의 증가량(&#916;R&#178;)이 유의한지를 검정합니다. 변수 선택을 통계적 기준(p-value)으로 자동화하는 단계적 회귀와 달리, 투입 순서를 연구자의 이론에 따라 미리 정한다는 점이 다릅니다.</p>`,
  formula: `&#916;R&#178; = R&#178;&#8342;&#8290;&#8340;&#8333;&#8340;&#8331; &#8722; R&#178;&#8342;&#8331;&#8321; &nbsp;(모형 m의 결정계수 증가분에 대한 F검정)`,
  features: `<p><strong>장점</strong> — 이론적으로 중요한 변수군의 추가 설명력을 통계적으로 검정할 수 있어 사회과학 연구에서 인과적 서술에 흔히 사용됩니다.</p><p><strong>단점</strong> — 블록 투입 순서를 연구자가 주관적으로 정해야 하고, 다중공선성이 있으면 블록 간 설명력 배분이 왜곡될 수 있습니다.</p>`,
  applications: `<p>심리학·경영학 등에서 인구통계 변수를 통제한 뒤 심리적 변수의 추가 설명력을 검정하는 위계적 회귀분석이 대표 사례이며, scikit-learn에는 전용 클래스가 없어 <code>statsmodels.OLS</code>로 여러 모형을 순차 적합해 &#916;R&#178;을 직접 계산하는 방식으로 구현합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'quantile-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Quantile Regression : 분위수 회귀',
  subtitle: '조건부 평균이 아닌 조건부 분위수(중앙값, 90분위수 등)를 직접 추정하는 회귀 기법',
  overview: `<p>일반 최소제곱 회귀가 조건부 평균 E[y|X]를 추정하는 것과 달리, 분위수 회귀는 비대칭 절대오차인 핀볼 손실(pinball loss)을 최소화해 임의의 분위수 &#964;(예: 중앙값, 상위 10%)에서의 조건부 분포를 추정합니다. 이상치에 덜 민감하고 분포의 형태(비대칭·이분산)를 함께 파악할 수 있습니다.</p>`,
  formula: `&#961;&#964;(u) = u&#183;(&#964;&#8722;&#120143;(u&lt;0)) &nbsp;(&#964;: 목표 분위수, 핀볼/체크 손실함수)`,
  features: `<p><strong>장점</strong> — 이상치에 강건하고 평균만으로는 드러나지 않는 분포의 꼬리·비대칭 구조를 파악할 수 있습니다.</p><p><strong>단점</strong> — 분위수마다 별도 모델을 적합해야 해 여러 분위수를 동시에 볼 때 계산량이 늘고, 분위수 간 교차(crossing) 문제가 발생할 수 있습니다.</p>`,
  applications: `<p>전력 수요의 최대부하(상위 분위수) 예측, 부동산 가격의 하위·상위 구간 예측 등에 사용되며 scikit-learn의 <code>QuantileRegressor</code>로 바로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'QuantileRegressor',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#quantile-regression',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.QuantileRegressor.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_quantile_regression.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'robust-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Robust Regression : 강건 회귀',
  subtitle: '이상치의 영향을 최소화하도록 설계된 손실함수·추정법을 사용하는 회귀 기법의 총칭',
  overview: `<p>표준 최소제곱법은 오차 제곱합을 최소화하기 때문에 이상치 하나에도 계수 추정이 크게 흔들립니다. 강건 회귀는 RANSAC(무작위 표본합의), Theil-Sen(쌍별 기울기의 중앙값), Huber 손실(제곱오차와 절대오차를 혼합) 등으로 이상치의 영향력을 제한합니다.</p>`,
  formula: `L&#8330;&#8329;&#8348;&#8329;&#8342;(e) = e&#178;/2 (|e|&#8804;&#948;), &#948;(|e|&#8722;&#948;/2) (|e|&gt;&#948;) &nbsp;(Huber 손실)`,
  features: `<p><strong>장점</strong> — 이상치나 오염된 데이터가 섞여 있어도 계수 추정이 크게 왜곡되지 않습니다.</p><p><strong>단점</strong> — 이상치가 전혀 없는 깨끗한 데이터에서는 일반 최소제곱보다 효율(분산)이 다소 떨어질 수 있습니다.</p>`,
  applications: `<p>센서 잡음이나 오염된 라벨이 섞인 데이터, 컴퓨터 비전의 기하 모델 추정 등에 사용되며 scikit-learn의 <code>RANSACRegressor</code>·<code>TheilSenRegressor</code>·<code>HuberRegressor</code>로 바로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'RANSACRegressor / TheilSenRegressor / HuberRegressor',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#robustness-regression-outliers-and-modeling-errors',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.HuberRegressor.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_robust_fit.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'stepwise-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Stepwise Regression : 단계적 회귀',
  subtitle: 'AIC·p-value 등의 기준으로 변수를 한 번에 하나씩 추가·제거하며 최적 변수 조합을 탐색하는 변수 선택법',
  overview: `<p>전진선택(변수를 하나씩 추가), 후진제거(모든 변수에서 하나씩 제거), 또는 두 방식을 번갈아 적용하는 단계적 방식으로, 매 단계 통계적 유의성이나 정보기준(AIC/BIC)이 가장 개선되는 변수를 선택해 모형에 반영합니다.</p>`,
  formula: `AIC = 2k &#8722; 2logL &nbsp;(k: 파라미터 수, 매 단계 AIC가 최소가 되는 변수 조합 탐색)`,
  features: `<p><strong>장점</strong> — 변수가 많을 때 모형을 자동으로 단순화하고 해석 가능한 부분집합을 얻을 수 있습니다.</p><p><strong>단점</strong> — 탐욕적(greedy) 탐색이라 전역 최적해를 보장하지 못하고, 반복적 가설검정으로 인한 p-value 왜곡(다중검정 문제)이 발생할 수 있습니다.</p>`,
  applications: `<p>전통적으로 R의 <code>step()</code> 함수나 SPSS에서 널리 쓰였으며, Python에서는 scikit-learn에 전용 클래스가 없어 <code>mlxtend</code>의 <code>SequentialFeatureSelector</code>나 statsmodels 기반 커스텀 구현으로 대체합니다. 최근에는 라쏘 등 정규화 기반 변수 선택이 더 선호됩니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},

/* ========================================================= */
/* [2.1.4] 다항 선형 회귀 (5) */
/* ========================================================= */
{
  id: 'kernel-polynomial-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Kernel Polynomial Regression : 커널 다항 회귀',
  subtitle: '다항 커널을 이용해 원본 특성을 명시적으로 확장하지 않고도 다항식 형태의 비선형 관계를 학습하는 회귀',
  overview: `<p>다항 특성을 직접 만들어 붙이는 대신, 커널 함수 K(x,x&#8242;)=(&#947;x&#183;x&#8242;+r)&#7480; 를 이용해 고차원 다항 특성 공간에서의 내적을 저차원 연산만으로 계산하는 커널 트릭을 적용합니다. 특성 수가 폭발적으로 늘어나는 고차 다항식에서도 계산 효율을 유지합니다.</p>`,
  formula: `K(x,x&#8242;) = (&#947;&#183;x&#7488;x&#8242;+r)&#7480; &nbsp;(d: 차수, &#947;·r: 커널 파라미터)`,
  features: `<p><strong>장점</strong> — 명시적 다항 특성을 만들지 않아도 되어 고차수에서도 메모리·연산 효율이 좋습니다.</p><p><strong>단점</strong> — 커널 파라미터(차수, &#947;, r)를 교차검증으로 튜닝해야 하고 모델 해석은 명시적 다항 회귀보다 어렵습니다.</p>`,
  applications: `<p>scikit-learn의 <code>SVR(kernel='poly')</code>이나 <code>KernelRidge(kernel='poly')</code>로 바로 적합할 수 있으며, 변수 간 상호작용이 복잡한 화학·재료공학 데이터 회귀에 사용됩니다.</p>`,
  sklearnFunction: "KernelRidge(kernel='poly') / SVR(kernel='poly')",
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/kernel_ridge.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.kernel_ridge.KernelRidge.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_kernel_ridge_regression.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'multivariate-polynomial-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Multivariate Polynomial Regression : 다변량 다항 회귀',
  subtitle: '2개 이상의 설명변수와 그 교호작용·거듭제곱 항을 포함해 비선형 관계를 학습하는 다항 회귀',
  overview: `<p>여러 설명변수 각각의 거듭제곱 항뿐 아니라 변수 간 곱(교호작용) 항까지 특성으로 만든 뒤 선형회귀를 적용합니다. 특성 공간을 확장한 뒤에는 여전히 계수에 대해 선형이므로 최소제곱법으로 그대로 적합할 수 있습니다.</p>`,
  formula: `y&#770; = &#946;&#8320; + &#8721;&#8290;&#7522; &#946;&#7522;x&#7522; + &#8721;&#8290;&#7522;&#8804;&#7580; &#946;&#7522;&#7580;x&#7522;x&#7580; + &#8943; &nbsp;(교호작용·거듭제곱 항 포함)`,
  features: `<p><strong>장점</strong> — 변수 간 상호작용까지 반영해 단순 다항 회귀보다 표현력이 풍부합니다.</p><p><strong>단점</strong> — 변수·차수가 늘어나면 특성 수가 조합적으로 폭증(차원의 저주)해 과적합·다중공선성 위험이 커집니다.</p>`,
  applications: `<p>scikit-learn의 <code>PolynomialFeatures(degree=n, interaction_only=False)</code>를 <code>LinearRegression</code>과 파이프라인으로 연결해 구현하며, 여러 공정 변수가 상호작용하는 실험설계(반응표면법) 분석에 사용됩니다.</p>`,
  sklearnFunction: 'PolynomialFeatures + LinearRegression',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#polynomial-regression-extending-linear-models-with-basis-functions',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_polynomial_interpolation.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'orthogonal-polynomial-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Orthogonal Polynomial Regression : 직교 다항 회귀',
  subtitle: '거듭제곱 대신 서로 직교하는 다항 기저(르장드르 등)를 사용해 수치적으로 안정적으로 적합하는 다항 회귀',
  overview: `<p>일반 다항 회귀에서 사용하는 1,x,x&#178;,x&#179;,&#8943; 항들은 차수가 높아질수록 서로 강하게 상관되어 계수 추정이 불안정해집니다(다중공선성). 직교 다항 회귀는 이 기저를 서로 직교하도록 재구성(예: 르장드르 다항식)하여 계수 추정과 항 추가·제거를 수치적으로 안정적으로 만듭니다.</p>`,
  formula: `y&#770; = &#8721;&#8290;&#7532;&#8320;&#7477; &#945;&#7532;P&#7532;(x) &nbsp;(P&#7532;: k차 직교다항식, &#8747;P&#7522;(x)P&#7580;(x)dx=0 for i&#8800;j)`,
  features: `<p><strong>장점</strong> — 차수를 높여도 기존 항의 계수가 바뀌지 않고 수치적으로 안정적이어서 고차항을 단계적으로 추가·검정하기 쉽습니다.</p><p><strong>단점</strong> — 원래 척도의 계수로 직접 해석하기 어려워 예측 후 재변환이 필요합니다.</p>`,
  applications: `<p>R의 <code>poly(x, degree, raw=FALSE)</code>가 대표적 구현이며, Python에서는 <code>numpy.polynomial.legendre</code> 등으로 직교 기저를 생성한 뒤 scikit-learn <code>LinearRegression</code>에 입력하는 방식으로 구현합니다. scikit-learn 자체에는 전용 직교다항 변환기가 없습니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'pls-polynomial-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'PLS(Partial Least Squares)-Polynomial Regression : 부분 최소제곱 다항 회귀',
  subtitle: '다항 특성 확장 후 PLS로 차원을 축소해 다중공선성이 심한 다항 항들을 안정적으로 적합하는 방법',
  overview: `<p>다항 특성(거듭제곱·교호작용 항)을 생성하면 항들 간 상관이 매우 커져 일반 최소제곱으로는 계수가 불안정해집니다. PLS 회귀는 예측변수와 반응변수의 공분산을 최대화하는 잠재변수(성분)를 추출해 이 다중공선성 문제를 우회하면서 다항적 비선형성을 반영합니다.</p>`,
  formula: `X = TP&#7488; + E,&nbsp; y = TQ&#7488; + F &nbsp;(T: PLS 잠재성분, 다항 확장된 X에 대해 적용)`,
  features: `<p><strong>장점</strong> — 다항 특성 간 심한 다중공선성에도 안정적인 계수를 얻으며 소수의 잠재성분만으로 차원을 축소합니다.</p><p><strong>단점</strong> — 잠재성분 수를 교차검증으로 정해야 하고 개별 다항 항의 계수 해석은 어려워집니다.</p>`,
  applications: `<p>분광분석(화학계량학)에서 파장별 신호에 다항 보정을 적용한 뒤 PLS로 성분을 예측하는 데 사용되며, scikit-learn의 <code>PolynomialFeatures</code>와 <code>PLSRegression</code>을 파이프라인으로 연결해 구현합니다.</p>`,
  sklearnFunction: 'PolynomialFeatures + PLSRegression',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/cross_decomposition.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.cross_decomposition.PLSRegression.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'univariate-polynomial-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Univariate Polynomial Regression : 단변량 다항 회귀',
  subtitle: '단일 설명변수의 거듭제곱 항만으로 곡선 형태의 관계를 학습하는 가장 단순한 다항 회귀',
  overview: `<p>하나의 설명변수 x에 대해 x, x&#178;, x&#179;, &#8943;, x&#7480; 항을 특성으로 추가한 뒤 선형회귀를 적용해 곡선을 적합합니다. 특성 자체는 비선형이지만 계수에 대해서는 선형이므로 최소제곱법을 그대로 사용할 수 있습니다.</p>`,
  formula: `y&#770; = &#946;&#8320; + &#946;&#8321;x + &#946;&#8322;x&#178; + &#8943; + &#946;&#7480;x&#7480;`,
  features: `<p><strong>장점</strong> — 구현이 간단하고 계수의 부호·크기로 곡률의 방향을 직관적으로 해석할 수 있습니다.</p><p><strong>단점</strong> — 차수가 높아지면 훈련 구간을 벗어난 외삽에서 값이 급격히 발산하는 등 불안정해질 수 있습니다.</p>`,
  applications: `<p>scikit-learn의 <code>PolynomialFeatures(degree=n)</code>과 <code>LinearRegression</code>을 결합해 구현하며, 시간에 따른 성장곡선·감쇠곡선 등 단일 변수의 비선형 추세를 설명하는 데 사용됩니다.</p>`,
  sklearnFunction: 'PolynomialFeatures + LinearRegression',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#polynomial-regression-extending-linear-models-with-basis-functions',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_polynomial_interpolation.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},

/* ========================================================= */
/* [2.1.5] 정규화 (벌점부여) 선형 회귀 (8) */
/* ========================================================= */
{
  id: 'adaptive-lasso-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Adaptive Lasso Regression : 적응적 라쏘 회귀',
  subtitle: '변수별 가중치를 다르게 부여해 라쏘의 일관성(oracle property) 문제를 보완한 개선된 라쏘 회귀',
  overview: `<p>표준 라쏘는 모든 계수에 동일한 벌점을 적용해 진짜 중요한 변수까지 과도하게 축소(bias)할 수 있습니다. 적응적 라쏘는 초기 추정치(예: 최소제곱 또는 릿지 계수)의 역수를 가중치로 사용해, 이미 크다고 판단된 계수에는 약한 벌점을, 작은 계수에는 강한 벌점을 부여함으로써 오라클 성질(변수 선택 일관성)을 확보합니다.</p>`,
  formula: `min&#8342; ||y&#8722;X&#946;||&#178;&#8322; + &#955;&#8721;&#8290;&#7522; w&#7522;|&#946;&#7522;| &nbsp;(w&#7522;=1/|&#946;&#770;&#7522;&#8290;&#8305;&#8331;&#8305;&#8340;&#8339;|&#7488;, &#947;&gt;0)`,
  features: `<p><strong>장점</strong> — 표준 라쏘보다 변수 선택 일관성이 이론적으로 보장되고 큰 계수의 편향을 줄입니다.</p><p><strong>단점</strong> — 초기 추정치가 필요해 2단계 절차가 되고, 초기 추정치의 품질에 최종 결과가 민감합니다.</p>`,
  applications: `<p>scikit-learn에는 전용 클래스가 없어 초기 릿지·OLS 계수로 특성을 가중 스케일링한 뒤 <code>Lasso</code>를 적용하는 방식으로 구현하며, 유전체 데이터처럼 소수의 핵심 변수만 정확히 골라내야 하는 고차원 변수 선택에 사용됩니다.</p>`,
  sklearnFunction: 'Lasso (가중치 재조정 방식으로 근사 구현)',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#lasso',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'elastic-net-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Elastic Net Regression(L1+L2) : 엘라스틱넷 회귀',
  subtitle: 'L1(라쏘)과 L2(릿지) 벌점을 함께 사용해 변수 선택과 계수 축소를 동시에 수행하는 정규화 회귀',
  overview: `<p>라쏘 단독으로는 상관관계가 높은 변수군 중 하나만 임의로 선택하고 나머지를 0으로 만드는 불안정성이 있습니다. 엘라스틱넷은 L1과 L2 벌점을 혼합비율 &#961;로 함께 적용해, 상관된 변수들을 그룹으로 함께 선택하면서도 변수 선택 효과를 유지합니다.</p>`,
  formula: `min&#8342; ||y&#8722;X&#946;||&#178;&#8322; + &#945;&#961;||&#946;||&#8321; + &#945;(1&#8722;&#961;)/2&#183;||&#946;||&#178;&#8322;`,
  features: `<p><strong>장점</strong> — 상관된 변수 그룹을 함께 선택해 라쏘보다 안정적이며, 변수 수가 표본 수보다 많은 경우(p&gt;n)에도 잘 작동합니다.</p><p><strong>단점</strong> — 정규화 강도 &#945;와 혼합비율 &#961; 두 하이퍼파라미터를 함께 튜닝해야 합니다.</p>`,
  applications: `<p>유전체·텍스트 데이터처럼 변수 간 상관이 높고 변수 수가 많은 고차원 회귀에 널리 사용되며 scikit-learn의 <code>ElasticNet</code>/<code>ElasticNetCV</code>로 바로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'ElasticNet / ElasticNetCV',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#elastic-net',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_lasso_and_elasticnet.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'group-lasso-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Group Lasso Regression : 그룹 라쏘 회귀',
  subtitle: '사전에 정의된 변수 그룹 단위로 계수를 통째로 0으로 만들어 그룹 수준의 변수 선택을 수행하는 정규화 회귀',
  overview: `<p>범주형 변수를 원-핫 인코딩한 여러 더미변수나 다항식의 여러 차수 항처럼 "논리적으로 하나의 단위"를 이루는 변수 묶음이 있을 때, 개별 계수가 아닌 그룹 전체의 L2 노름에 벌점을 부여해 그룹째로 선택하거나 제거합니다.</p>`,
  formula: `min&#8342; ||y&#8722;X&#946;||&#178;&#8322; + &#955;&#8721;&#8290;&#8290;&#7580;&#8290;&#8320;&#7580; &#8730;p&#7580;&#183;||&#946;&#8296;&#7580;&#8298;||&#8322; &nbsp;(&#946;&#8296;&#7580;&#8298;: g번째 그룹의 계수 벡터)`,
  features: `<p><strong>장점</strong> — 범주형 변수의 더미항이나 다항 항 등 자연스러운 그룹 구조를 계수 선택에 반영할 수 있습니다.</p><p><strong>단점</strong> — 그룹 내부에서는 희소성을 강제하지 않아 그룹이 선택되면 그룹 내 모든 계수가 함께 남습니다(그룹 내 희소성은 Sparse Group Lasso로 보완).</p>`,
  applications: `<p>유전자 경로(pathway) 단위 변수 선택, 범주형 변수가 많은 회귀 문제에 사용되며, scikit-learn과 API 호환되는 <code>group-lasso</code>·<code>celer</code> 파이썬 패키지의 <code>GroupLasso</code> 클래스로 구현할 수 있습니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'lasso-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Lasso Regression(L1) : 라쏘 회귀',
  subtitle: 'L1 벌점으로 불필요한 변수의 계수를 정확히 0으로 만들어 변수 선택을 겸하는 정규화 회귀',
  overview: `<p>계수의 절댓값 합(L1 노름)에 벌점을 부여하는 최소제곱 회귀로, 벌점의 기하학적 특성(모서리가 있는 제약영역) 덕분에 릿지와 달리 일부 계수를 정확히 0으로 축소합니다. 이 때문에 변수 선택과 계수 추정을 동시에 수행하는 임베디드 방식 특성 선택 기법으로도 쓰입니다.</p>`,
  formula: `min&#8342; ||y&#8722;X&#946;||&#178;&#8322; + &#955;||&#946;||&#8321;`,
  features: `<p><strong>장점</strong> — 불필요한 변수의 계수를 0으로 만들어 모델을 간결하게 하고 해석을 돕습니다.</p><p><strong>단점</strong> — 상관관계가 높은 변수 그룹 중 하나만 임의로 선택하는 경향이 있어 변수 선택이 불안정할 수 있습니다.</p>`,
  applications: `<p>변수 수가 매우 많은 유전체·텍스트 데이터의 특성 선택, 희소한 신호 복원 등에 널리 사용되며 scikit-learn의 <code>Lasso</code>/<code>LassoCV</code>로 바로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'Lasso / LassoCV',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#lasso',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_lasso_and_elasticnet.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'mcp-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'MCP(Minimax Concave Penalty) Regression : MCP 벌점 회귀',
  subtitle: '계수 크기가 커질수록 벌점 기울기를 완만하게 줄여 큰 계수의 편향을 최소화하는 비볼록 정규화 회귀',
  overview: `<p>라쏘의 L1 벌점은 계수 크기와 무관하게 일정한 기울기(&#955;)로 축소를 가하기 때문에 실제로 큰 진짜 계수까지 편향시킵니다. MCP는 계수 절댓값이 임계치 &#947;&#955;를 넘으면 벌점 기울기가 0으로 완만하게 줄어드는 비볼록 벌점을 사용해, 큰 계수는 거의 축소하지 않으면서 작은 계수만 강하게 0으로 미는 근사 불편(near-unbiased) 추정을 추구합니다.</p>`,
  formula: `P&#8341;&#8339;&#8331;(&#946;;&#955;,&#947;) = &#955;|&#946;|&#8722;&#946;&#178;/(2&#947;) (|&#946;|&#8804;&#947;&#955;), &#947;&#955;&#178;/2 (|&#946;|&gt;&#947;&#955;)`,
  features: `<p><strong>장점</strong> — 큰 계수의 축소 편향이 라쏘보다 작아 오라클 성질에 더 가까운 변수 선택이 가능합니다.</p><p><strong>단점</strong> — 벌점이 비볼록이라 전역 최적해 보장이 어렵고 초기값에 따라 결과가 달라질 수 있으며, 파이썬 생태계에는 성숙한 구현체가 부족합니다.</p>`,
  applications: `<p>고차원 유전체 데이터의 변수 선택 연구에서 주로 사용되며, R의 <code>ncvreg</code> 패키지가 대표 구현체입니다. scikit-learn에는 내장되어 있지 않습니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'ridge-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Ridge Regression(L2) : 릿지 회귀',
  subtitle: '계수 제곱합(L2 노름)에 벌점을 부여해 다중공선성을 완화하고 계수를 축소하는 정규화 회귀',
  overview: `<p>최소제곱 손실에 계수 제곱합 벌점을 더해, 변수 간 상관이 높거나 변수 수가 표본 수에 비해 많을 때도 안정적인 계수를 추정합니다. 벌점이 매끄러운(미분 가능한) 형태라 계수를 0으로 만들지는 않고 전체적으로 축소(shrinkage)합니다.</p>`,
  formula: `min&#8342; ||y&#8722;X&#946;||&#178;&#8322; + &#955;||&#946;||&#178;&#8322;`,
  features: `<p><strong>장점</strong> — 다중공선성이 있어도 계수 추정이 안정적이고 닫힌 형태(closed-form) 해가 존재해 계산이 빠릅니다.</p><p><strong>단점</strong> — 계수를 0으로 만들지 않아 변수 선택 효과는 없고 모든 변수를 모델에 남깁니다.</p>`,
  applications: `<p>다중공선성이 흔한 경제·사회과학 데이터, 변수 수가 많은 예측 문제의 베이스라인 정규화 기법으로 scikit-learn의 <code>Ridge</code>/<code>RidgeCV</code>가 널리 사용됩니다.</p>`,
  sklearnFunction: 'Ridge / RidgeCV',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#ridge-regression-and-classification',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_ridge_path.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'scad-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'SCAD(Smoothly Clipped Absolute Deviation) Regression : SCAD 벌점 회귀',
  subtitle: '작은 계수는 라쏘처럼, 큰 계수는 거의 벌점 없이 처리해 불편성과 희소성을 함께 만족시키는 비볼록 정규화 회귀',
  overview: `<p>Fan과 Li(2001)가 제안한 벌점으로, 계수 절댓값이 작을 때는 라쏘와 동일한 선형 벌점을 적용하다가 일정 구간을 지나면 이차함수로 매끄럽게 전환되고, 임계치를 넘으면 벌점이 상수(기울기 0)가 되어 큰 계수에는 사실상 벌점을 가하지 않습니다.</p>`,
  formula: `P&#8319;&#8342;&#8329;&#8332;(|&#946;|) = &#955;|&#946;| (|&#946;|&#8804;&#955;), 구간별 이차 보간 (&#955;&lt;|&#946;|&#8804;a&#955;), (a+1)&#955;&#178;/2 (|&#946;|&gt;a&#955;) &nbsp;(보통 a=3.7)`,
  features: `<p><strong>장점</strong> — 오라클 성질(불편성·희소성·점근적 정규성)을 만족하도록 설계되어 이론적으로 라쏘보다 우수한 변수 선택 성능을 보입니다.</p><p><strong>단점</strong> — 벌점이 비볼록이라 최적화가 어렵고(로컬 이차근사 등 특수 알고리즘 필요), 파이썬 생태계의 지원이 부족합니다.</p>`,
  applications: `<p>고차원 유전체·바이오마커 변수 선택 연구에서 주로 활용되며, R의 <code>ncvreg</code> 패키지가 대표 구현체입니다. scikit-learn에는 내장되어 있지 않습니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'sparse-group-lasso-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Sparse Group Lasso Regression : 희소 그룹 라쏘 회귀',
  subtitle: '그룹 단위 선택(그룹 라쏘)과 그룹 내부 변수 선택(라쏘)을 동시에 수행하는 혼합 정규화 회귀',
  overview: `<p>그룹 라쏘가 그룹 전체를 선택하거나 제거하는 데 그치는 반면, 희소 그룹 라쏘는 그룹 벌점과 개별 L1 벌점을 함께 부여해 선택된 그룹 안에서도 불필요한 개별 변수를 추가로 0으로 만듭니다.</p>`,
  formula: `min&#8342; ||y&#8722;X&#946;||&#178;&#8322; + &#945;&#955;&#8721;&#8290;&#7580; &#8730;p&#7580;&#183;||&#946;&#8296;&#7580;&#8298;||&#8322; + (1&#8722;&#945;)&#955;||&#946;||&#8321;`,
  features: `<p><strong>장점</strong> — 그룹 수준과 변수 수준 양쪽에서 희소성을 얻어 그룹 라쏘보다 더 해석 가능한 결과를 제공합니다.</p><p><strong>단점</strong> — 그룹 간 혼합비율 &#945;를 포함해 튜닝할 하이퍼파라미터가 늘어납니다.</p>`,
  applications: `<p>다중 오믹스 데이터처럼 그룹 구조와 그룹 내 희소성이 함께 필요한 유전체 연구에 사용되며, Python <code>group-lasso</code> 패키지가 Sparse Group Lasso를 scikit-learn 호환 API로 제공합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},

/* ========================================================= */
/* [2.1.6] 비선형 회귀 (12) */
/* ========================================================= */
{
  id: 'bayesian-nonlinear-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Bayesian Nonlinear Regression : 베이즈 비선형 회귀',
  subtitle: '비선형 함수에 대한 사전분포(가우시안 프로세스 등)를 두고 사후분포로 예측 불확실성까지 추정하는 회귀',
  overview: `<p>비선형 함수 자체를 확률변수로 취급해 함수공간에 대한 사전분포를 정의하고, 관측 데이터를 반영한 사후분포로부터 예측 평균과 신용구간을 함께 얻습니다. 대표적으로 가우시안 프로세스 회귀는 임의의 유한 관측점 집합이 다변량 정규분포를 따른다는 가정으로 비선형 함수를 베이즈적으로 추정합니다.</p>`,
  formula: `f &#8764; GP(m(x), k(x,x&#8242;)) &nbsp;(m: 평균함수, k: 공분산 커널함수)`,
  features: `<p><strong>장점</strong> — 예측값뿐 아니라 예측 불확실성(신용구간)을 자연스럽게 제공해 실험설계·최적화(베이지안 최적화)에 유용합니다.</p><p><strong>단점</strong> — 데이터 수가 늘어나면 커널 행렬 역산 비용(O(n&#179;))이 급격히 커져 대규모 데이터에는 근사기법이 필요합니다.</p>`,
  applications: `<p>실험 데이터가 적고 불확실성 정량화가 중요한 화학공정 최적화, 센서 보정 등에 사용되며, scikit-learn의 <code>GaussianProcessRegressor</code>로 바로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'GaussianProcessRegressor',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/gaussian_process.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/gaussian_process/plot_gpr_noisy_targets.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'deep-gaussian-process-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Deep Gaussian Process Regression : 딥 가우시안 프로세스 회귀',
  subtitle: '여러 층의 가우시안 프로세스를 쌓아 단일 GP보다 복잡한 비정상성(non-stationary) 함수를 표현하는 회귀',
  overview: `<p>한 층의 가우시안 프로세스 출력을 다음 층 가우시안 프로세스의 입력으로 사용하는 계층 구조로, 신경망의 층 구조를 GP에 적용한 형태입니다. 단일 GP가 가정하는 고정된 커널 하나로는 표현하기 어려운 비정상적(non-stationary)이고 복잡한 함수 형태를 표현할 수 있습니다.</p>`,
  formula: `f&#8317;&#8318;&#8317; = g&#8317;&#8318;&#8317;(f&#8317;&#8318;&#8331;&#8321;&#8317;), &nbsp; f&#8317;&#8318;&#8317; &#8764; GP(0, k&#8317;&#8318;&#8317;) &nbsp;(각 층의 사상 g&#8317;&#8318;&#8317;이 GP를 따름)`,
  features: `<p><strong>장점</strong> — 단일 GP보다 복잡하고 비정상적인 함수 관계를 표현할 수 있고 베이즈적 불확실성 정량화를 유지합니다.</p><p><strong>단점</strong> — 층이 깊어질수록 추론(변분추론)이 매우 복잡해지고 계산 비용이 커서 scikit-learn 등 전통 라이브러리에는 구현되어 있지 않습니다.</p>`,
  applications: `<p>복잡한 비정상 함수를 갖는 로보틱스 제어, 강화학습의 모델 기반 세계모델 학습 등에 연구적으로 사용되며, GPyTorch·GPflow 같은 전용 딥러닝 기반 GP 라이브러리로 구현합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'functional-data-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Functional Data Regression : 함수형 데이터 회귀',
  subtitle: '개별 관측치가 숫자 하나가 아닌 곡선(함수) 형태일 때 이를 예측변수 또는 반응변수로 다루는 회귀',
  overview: `<p>센서에서 연속적으로 측정된 시계열, 성장곡선처럼 각 관측 단위가 이산적인 벡터가 아니라 연속 함수로 간주되는 데이터를 다룹니다. 함수를 기저함수(B-스플라인, 푸리에 등)로 전개해 유한한 계수 벡터로 표현한 뒤 회귀를 적용하는 것이 일반적인 접근입니다.</p>`,
  formula: `y&#7522; = &#8747;&#946;(t)x&#7522;(t)dt + &#949;&#7522; &nbsp;(x&#7522;(t): 함수형 예측변수, &#946;(t): 함수형 계수)`,
  features: `<p><strong>장점</strong> — 시간에 따른 전체 변화 패턴을 하나의 예측변수로 자연스럽게 표현할 수 있어 시계열·곡선 데이터의 정보 손실을 줄입니다.</p><p><strong>단점</strong> — 기저함수 선택과 평활 정규화가 필요하고, 일반 표 형태 데이터를 다루는 라이브러리로는 바로 처리할 수 없습니다.</p>`,
  applications: `<p>웨어러블 센서의 연속 신호 분석, 성장곡선 기반 의학 연구 등에 사용되며 Python <code>scikit-fda</code> 라이브러리가 scikit-learn과 유사한 API로 함수형 데이터 회귀를 제공합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'gamlss-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'GAMLSS(Generalized Additive Models for Location, Scale and Shape) : 위치-규모-형상 회귀',
  subtitle: '평균뿐 아니라 분산·왜도·첨도 등 분포의 모든 모수를 설명변수의 가법 함수로 모델링하는 회귀 프레임워크',
  overview: `<p>일반 GLM/GAM이 분포의 평균(위치 모수)만 설명변수의 함수로 두는 것과 달리, GAMLSS는 분산(규모)·왜도·첨도 등 분포를 구성하는 모든 모수 각각에 대해 별도의 가법모형(스플라인)을 적합할 수 있습니다. 매우 유연한 분포족(4모수 분포 등)까지 다룰 수 있어 GLM/GAM의 상위 확장으로 여겨집니다.</p>`,
  formula: `g&#8320;(&#956;)=&#8721;f&#8320;&#7580;(x&#7580;), g&#8321;(&#963;)=&#8721;f&#8321;&#7580;(x&#7580;), g&#8322;(&#957;)=&#8943;, g&#8323;(&#964;)=&#8943; &nbsp;(위치·규모·왜도·첨도 각각 별도 가법모형)`,
  features: `<p><strong>장점</strong> — 평균 외에 분산·비대칭성까지 설명변수에 따라 달라지는 매우 유연한 분포 형태를 표현합니다.</p><p><strong>단점</strong> — 모수마다 별도 모형을 적합해야 해 계산 비용과 과적합 위험이 크고, 파이썬 생태계에 성숙한 구현이 부족합니다.</p>`,
  applications: `<p>소아 성장기준표(WHO 성장곡선)처럼 나이에 따라 분포의 평균뿐 아니라 산포·비대칭까지 달라지는 참조곡선 추정에 널리 쓰이며, R의 <code>gamlss</code> 패키지가 사실상 표준 구현체입니다. scikit-learn·Python 생태계에는 대응하는 라이브러리가 마땅치 않습니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'high-order-polynomial-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'High-order Polynomial Regression : 고차 다항 회귀',
  subtitle: '4차 이상의 높은 차수 항을 사용해 매우 굴곡진 비선형 관계를 표현하는 다항 회귀',
  overview: `<p>차수를 높일수록 훈련 데이터의 국소적 굴곡까지 세밀하게 따라갈 수 있지만, 룽게 현상(Runge's phenomenon)처럼 구간 경계 근처에서 값이 크게 진동하는 문제가 함께 커집니다. 편향-분산 트레이드오프에서 분산이 급격히 커지는 대표적 사례로 다뤄집니다.</p>`,
  formula: `y&#770; = &#946;&#8320; + &#946;&#8321;x + &#8943; + &#946;&#7480;x&#7480; &nbsp;(d &#8805; 4)`,
  features: `<p><strong>장점</strong> — 훈련 구간 내 복잡한 곡률을 매우 유연하게 표현할 수 있습니다.</p><p><strong>단점</strong> — 차수가 높을수록 과적합·수치적 불안정성(다중공선성)·외삽 발산 위험이 커져 실무에서는 스플라인이나 정규화와 함께 사용해야 합니다.</p>`,
  applications: `<p>scikit-learn의 <code>PolynomialFeatures(degree&gt;=4)</code>와 <code>Ridge</code>/<code>Lasso</code>를 결합해 과적합을 억제하며 사용하는 것이 일반적이며, 교육 목적으로 편향-분산 트레이드오프를 설명할 때 자주 인용됩니다.</p>`,
  sklearnFunction: 'PolynomialFeatures + Ridge/Lasso',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#polynomial-regression-extending-linear-models-with-basis-functions',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/model_selection/plot_underfitting_overfitting.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'kernel-based-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Kernel-based Regression : 커널 기반 회귀',
  subtitle: '커널 함수로 정의된 고차원(암묵적) 특성 공간에서 선형 회귀를 수행해 비선형 관계를 학습하는 방법',
  overview: `<p>RBF·다항 등 커널 함수를 통해 원본 입력을 암묵적인 고차원 특성 공간으로 매핑한 뒤, 그 공간에서 선형 회귀(릿지 등)를 수행합니다. 커널 트릭 덕분에 고차원 특성을 명시적으로 계산하지 않고도 두 점 사이의 내적만으로 비선형 관계를 학습할 수 있습니다.</p>`,
  formula: `f(x) = &#8721;&#8290;&#7522; &#945;&#7522;K(x,x&#7522;) &nbsp;(K: 커널함수, &#945;: 쌍대문제 해)`,
  features: `<p><strong>장점</strong> — RBF 등 다양한 커널로 임의의 매끄러운 비선형 관계를 표현할 수 있고 이론적 기반(재생커널 힐베르트 공간)이 탄탄합니다.</p><p><strong>단점</strong> — 훈련 샘플 수가 많아지면 커널 행렬 크기가 O(n&#178;)로 커져 메모리·연산 부담이 큽니다.</p>`,
  applications: `<p>scikit-learn의 <code>KernelRidge</code>·<code>SVR</code>이 대표 구현체이며, 화학계량학·재료물성 예측처럼 표본 수는 적고 비선형성이 강한 회귀 문제에 자주 사용됩니다.</p>`,
  sklearnFunction: 'KernelRidge / SVR',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/kernel_ridge.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.kernel_ridge.KernelRidge.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_kernel_ridge_regression.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'mixture-of-nonlinear-regressions',
  category: 'sup',
  subcategory: 'regression',
  title: 'Mixture of Nonlinear Regressions : 혼합 비선형 회귀',
  subtitle: '데이터가 서로 다른 비선형 회귀 관계를 갖는 여러 잠재 하위집단에서 나왔다고 가정하는 혼합모형',
  overview: `<p>전체 데이터가 하나의 회귀식으로 설명되지 않고, 관측되지 않은 잠재 그룹마다 서로 다른 비선형 회귀 관계를 따른다고 가정합니다. EM 알고리즘으로 각 관측치가 어느 그룹에 속할 확률과 그룹별 회귀계수를 동시에 추정합니다.</p>`,
  formula: `p(y|x) = &#8721;&#8290;&#7532;&#8320;&#7480; &#960;&#7532;&#183;f&#7532;(y|x;&#952;&#7532;) &nbsp;(&#960;&#7532;: 그룹 k의 혼합비율, f&#7532;: 그룹별 비선형 회귀 분포)`,
  features: `<p><strong>장점</strong> — 데이터 안의 이질적인 하위 그룹별로 서로 다른 함수 관계를 발견하고 각각을 별도로 모델링할 수 있습니다.</p><p><strong>단점</strong> — 그룹 수를 미리 정하거나 정보기준으로 탐색해야 하고 EM 알고리즘이 지역해에 수렴할 위험이 있습니다.</p>`,
  applications: `<p>서로 다른 반응 패턴을 보이는 하위 고객군의 수요 곡선 추정 등에 사용되며, scikit-learn에는 전용 구현이 없어 R의 <code>flexmix</code> 패키지나 PyTorch 기반 혼합전문가(mixture-of-experts) 구현으로 다룹니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'neural-network-based-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Neural Network-based Regression : 신경망 기반 회귀',
  subtitle: '다층 퍼셉트론 등 신경망으로 임의의 복잡한 비선형 함수를 근사해 연속값을 예측하는 회귀',
  overview: `<p>은닉층의 비선형 활성화함수(ReLU 등)를 여러 층 쌓아 보편근사정리에 따라 임의의 연속함수를 근사할 수 있습니다. 출력층에 활성화함수를 두지 않고 항등함수를 사용해 연속적인 반응변수를 직접 예측합니다.</p>`,
  formula: `y&#770; = W&#8323;&#8290;&#963;(W&#8322;&#183;&#963;(W&#8321;x+b&#8321;)+b&#8322;)+b&#8323; &nbsp;(&#963;: 비선형 활성화함수)`,
  features: `<p><strong>장점</strong> — 변수 간 복잡한 비선형·교호작용을 자동으로 학습해 표현력이 매우 높습니다.</p><p><strong>단점</strong> — 표본 수가 적으면 과적합되기 쉽고 계수 기반 해석이 어려운 블랙박스 모델입니다.</p>`,
  applications: `<p>scikit-learn의 <code>MLPRegressor</code>로 바로 적합할 수 있으며, 수요 예측·에너지 소비 예측 등 비선형성이 강한 대규모 회귀 문제에 사용됩니다.</p>`,
  sklearnFunction: 'MLPRegressor',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/neural_networks_supervised.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPRegressor.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'nonlinear-least-squares-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Nonlinear Least Squares Regression : 비선형 최소제곱 회귀',
  subtitle: '계수에 대해 비선형인 함수식(지수·로지스틱 곡선 등)을 반복적 수치최적화로 직접 적합하는 회귀',
  overview: `<p>다항 회귀처럼 특성을 확장해 선형화하는 대신, y=f(x;&#952;) 형태의 함수식을 그대로 두고 잔차 제곱합을 최소화하는 &#952;를 Gauss-Newton·Levenberg-Marquardt 등 반복적 수치최적화로 직접 찾습니다. 함수 형태를 도메인 지식으로 미리 정할 수 있다는 점이 특징입니다.</p>`,
  formula: `min&#8341; &#8721;&#8290;&#7522; (y&#7522;&#8722;f(x&#7522;;&#952;))&#178; &nbsp;(f: 비선형 파라메트릭 함수)`,
  features: `<p><strong>장점</strong> — 물리적·생물학적 의미가 있는 함수 형태(예: 미카엘리스-멘텐 방정식)를 그대로 반영해 파라미터가 직접 해석 가능합니다.</p><p><strong>단점</strong> — 초기값에 따라 지역해에 수렴할 수 있고, 함수 형태를 사전에 알아야 적용할 수 있습니다.</p>`,
  applications: `<p>약물동태학의 반응곡선, 화학반응 속도식 적합 등에 사용되며 Python <code>scipy.optimize.curve_fit</code>이 표준 도구입니다. scikit-learn은 일반적인 비선형 최소제곱 인터페이스를 별도로 제공하지 않습니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'physics-informed-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Physics-Informed Regression : 물리정보 기반 회귀',
  subtitle: '데이터 적합 손실에 지배방정식(편미분방정식) 잔차 항을 함께 넣어 물리 법칙을 만족하도록 학습하는 회귀',
  overview: `<p>신경망(PINN, Physics-Informed Neural Network)의 손실함수에 관측 데이터와의 오차뿐 아니라, 자동미분으로 계산한 예측함수가 알려진 지배방정식(예: 열전도 방정식)을 얼마나 위반하는지를 나타내는 잔차 항을 함께 포함시킵니다. 이를 통해 데이터가 부족한 영역에서도 물리 법칙에 부합하는 예측을 얻습니다.</p>`,
  formula: `L = L&#8290;&#8296;&#8330;&#8348;&#8330;(&#952;) + &#955;&#183;L&#8290;&#8333;&#8322;&#8330;&#8331;&#8330;(&#952;) &nbsp;(L&#8290;&#8333;&#8322;&#8330;&#8331;&#8330;: 지배방정식 잔차의 제곱합)`,
  features: `<p><strong>장점</strong> — 관측 데이터가 희소한 영역에서도 물리 법칙으로 예측을 정규화해 일반화 성능을 높이고 물리적으로 타당한 해를 보장합니다.</p><p><strong>단점</strong> — 지배방정식을 명시적으로 알아야 하고, 데이터 손실과 물리 손실의 가중치 &#955; 균형을 맞추는 것이 까다롭습니다.</p>`,
  applications: `<p>유체역학·열전달 시뮬레이션 대체모델, 신소재의 물성 예측 등에 사용되며 Python <code>DeepXDE</code>·<code>PINA</code> 라이브러리가 대표 구현체입니다. scikit-learn에는 대응 기능이 없습니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'robust-nonlinear-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Robust Nonlinear Regression : 강건 비선형 회귀',
  subtitle: '비선형 최소제곱에 이상치에 덜 민감한 손실함수를 적용해 오염된 데이터에서도 안정적으로 적합하는 회귀',
  overview: `<p>비선형 함수식은 그대로 유지하되, 잔차 제곱합 대신 Huber·soft-L1·Cauchy 등 이상치의 영향력을 제한하는 손실함수를 사용해 파라미터를 추정합니다. 소수의 극단적 이상치가 전체 곡선 적합을 왜곡하는 것을 방지합니다.</p>`,
  formula: `min&#8341; &#8721;&#8290;&#7522; &#961;(y&#7522;&#8722;f(x&#7522;;&#952;)) &nbsp;(&#961;: Huber/soft-L1 등 강건 손실함수)`,
  features: `<p><strong>장점</strong> — 측정 오류나 극단치가 섞인 실험 데이터에서도 곡선 파라미터가 크게 왜곡되지 않습니다.</p><p><strong>단점</strong> — 손실함수 종류와 스케일 파라미터를 선택해야 하며 일반 비선형 최소제곱보다 계산이 다소 복잡합니다.</p>`,
  applications: `<p>잡음이 많은 센서 데이터의 곡선 적합, 이상치가 흔한 생물학적 성장곡선 추정 등에 사용되며 Python <code>scipy.optimize.least_squares</code>의 <code>loss='huber'</code>/<code>'soft_l1'</code>/<code>'cauchy'</code> 옵션으로 구현합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'spline-based-regression',
  category: 'sup',
  subcategory: 'regression',
  title: 'Spline-based Regression : 스플라인 기반 회귀',
  subtitle: '구간별 매끄럽게 이어지는 조각별 다항식(스플라인)으로 국소적 비선형성을 유연하게 표현하는 회귀',
  overview: `<p>전체 구간에 하나의 고차 다항식을 적합하는 대신, 여러 매듭(knot) 사이를 저차 다항식으로 나눠 적합하고 매듭에서 매끄럽게 이어지도록(연속·미분가능) 제약합니다. 고차 다항 회귀에서 나타나는 룽게 현상 없이 국소적인 비선형 패턴을 안정적으로 표현합니다.</p>`,
  formula: `y&#770; = &#8721;&#8290;&#7532; &#946;&#7532;B&#7532;(x) &nbsp;(B&#7532;: B-스플라인 기저함수)`,
  features: `<p><strong>장점</strong> — 다항 회귀보다 수치적으로 안정적이고 외삽 특성이 좋으며, 매듭 위치·개수로 유연성을 세밀하게 조절할 수 있습니다.</p><p><strong>단점</strong> — 매듭의 수와 위치, 스플라인 차수 등 추가 하이퍼파라미터를 선택해야 합니다.</p>`,
  applications: `<p>scikit-learn의 <code>SplineTransformer</code>를 <code>LinearRegression</code>/<code>Ridge</code>와 결합해 구현하며, 계절성이 있는 시계열 추세나 비선형 용량곡선 추정 등에 사용됩니다.</p>`,
  sklearnFunction: 'SplineTransformer + LinearRegression',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/preprocessing.html#generating-polynomial-features',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.SplineTransformer.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_polynomial_interpolation.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},

/* ========================================================= */
/* [2.2.1] 분류 — 확률적 판별 (4) */
/* ========================================================= */
{
  id: 'bayesian-logistic-regression',
  category: 'sup',
  subcategory: 'classification',
  title: 'Bayesian Logistic Regression : 베이즈 로지스틱 회귀',
  subtitle: '로지스틱 회귀 계수에 사전분포를 부여해 계수의 불확실성까지 함께 추정하는 베이즈 분류 모형',
  overview: `<p>고전적 로지스틱 회귀는 최대우도추정으로 계수 점추정치 하나만 제공하지만, 베이즈 로지스틱 회귀는 계수에 사전분포(가우시안 등)를 두고 MCMC·라플라스 근사·변분추론으로 사후분포를 추정합니다. 이를 통해 예측확률의 신용구간까지 함께 제공할 수 있습니다.</p>`,
  formula: `p(&#946;|y,X) &#8733; &#8719;&#8290;&#7522; &#963;(x&#7522;&#7488;&#946;)&#8319;&#7522;(1&#8722;&#963;(x&#7522;&#7488;&#946;))&#185;&#8331;&#7519;&#7522; &#183;p(&#946;) &nbsp;(&#963;: 로지스틱 함수)`,
  features: `<p><strong>장점</strong> — 계수·예측확률의 불확실성을 함께 정량화할 수 있고 소규모 데이터에서 사전분포로 과적합을 완화합니다.</p><p><strong>단점</strong> — 사후분포 계산에 MCMC 등 추가 연산이 필요해 대규모 데이터에서 느립니다.</p>`,
  applications: `<p>의료 진단처럼 예측의 신뢰도(불확실성)가 중요한 분야에서 사용되며, scikit-learn에는 전용 클래스가 없어 PyMC·NumPyro 같은 확률적 프로그래밍 라이브러리로 구현하는 것이 일반적입니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'logistic-regression',
  category: 'sup',
  subcategory: 'classification',
  title: 'Logistic Regression : 로지스틱 회귀',
  subtitle: '선형결합을 로지스틱(시그모이드) 함수로 변환해 이진 분류의 클래스 확률을 추정하는 가장 기본적인 분류 모형',
  overview: `<p>선형회귀의 출력을 시그모이드 함수에 통과시켜 0~1 사이의 확률로 변환한 뒤, 로그우도(교차 엔트로피)를 최대화(최소화)하는 방향으로 계수를 학습합니다. 이름에 회귀가 들어가지만 실제로는 분류 문제에 사용되는 판별 모형입니다.</p>`,
  formula: `P(y=1|x) = 1/(1+e&#8331;&#7509;&#7488;&#946;) &nbsp;(시그모이드 함수)`,
  features: `<p><strong>장점</strong> — 계수를 오즈비로 직관적으로 해석할 수 있고 예측확률을 직접 출력하며 계산이 빠릅니다.</p><p><strong>단점</strong> — 클래스 간 경계가 선형(또는 완만한 곡선)이라는 가정이 있어 복잡한 비선형 분류 경계는 표현하기 어렵습니다.</p>`,
  applications: `<p>이탈 예측, 신용 승인, 질병 유무 판별 등 이진 분류의 표준 베이스라인으로 scikit-learn의 <code>LogisticRegression</code>이 대표 구현체입니다.</p>`,
  sklearnFunction: 'LogisticRegression',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_iris_logistic.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'multinomial-logistic-softmax-regression',
  category: 'sup',
  subcategory: 'classification',
  title: 'Multinomial Logistic Regression / Softmax Regression : 다항 로지스틱 회귀 / 소프트맥스 회귀',
  subtitle: '3개 이상의 클래스에 대한 확률을 소프트맥스 함수로 동시에 추정하는 로지스틱 회귀의 다중클래스 확장',
  overview: `<p>이진 로지스틱 회귀를 K개 클래스로 확장한 형태로, 각 클래스에 대한 선형점수를 소프트맥스 함수에 통과시켜 모든 클래스 확률의 합이 1이 되도록 동시에 정규화합니다. 클래스별 이진분류기를 여러 개 따로 학습하는 One-vs-Rest 방식과 달리 하나의 통합 모형으로 학습합니다.</p>`,
  formula: `P(y=k|x) = e&#7563;&#7488;&#946;&#8342;/&#8721;&#8290;&#7580;&#8320;&#185;&#7480; e&#7563;&#7488;&#946;&#7580; &nbsp;(소프트맥스 함수, K: 클래스 수)`,
  features: `<p><strong>장점</strong> — 클래스가 3개 이상일 때 모든 클래스 확률을 일관되게 동시 추정하고 딥러닝 분류기의 출력층으로도 널리 쓰입니다.</p><p><strong>단점</strong> — 이진 로지스틱 회귀와 마찬가지로 선형 결정경계 가정을 가지며 클래스 수가 매우 많으면 계산량이 늘어납니다.</p>`,
  applications: `<p>손글씨 숫자 인식, 뉴스 카테고리 분류 등 다중클래스 분류의 표준 기법으로 scikit-learn의 <code>LogisticRegression(multi_class='multinomial')</code>과 신경망 출력층의 소프트맥스 함수로 널리 사용됩니다.</p>`,
  sklearnFunction: "LogisticRegression (multi_class='multinomial')",
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/linear_model/plot_logistic_multinomial.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'probit-regression',
  category: 'sup',
  subcategory: 'classification',
  title: 'Probit Regression : 프로빗 회귀',
  subtitle: '표준정규분포의 누적분포함수를 링크함수로 사용해 이진 반응 확률을 모델링하는 GLM',
  overview: `<p>로지스틱 회귀가 로지스틱 분포의 누적분포함수를 링크함수로 쓰는 것과 달리, 프로빗 회귀는 표준정규분포의 누적분포함수(&#934;)를 사용합니다. 잠재변수(latent variable) y*=X&#946;+&#949;가 0을 넘으면 y=1이 관측된다는 해석이 자연스러운 계량경제학적 모형입니다.</p>`,
  formula: `P(y=1|x) = &#934;(X&#946;) &nbsp;(&#934;: 표준정규분포 누적분포함수)`,
  features: `<p><strong>장점</strong> — 잠재변수 해석이 명확해 계량경제학에서 선호되며 로지스틱 회귀와 예측 성능이 대체로 유사합니다.</p><p><strong>단점</strong> — 계수를 오즈비로 직접 해석할 수 없어 로지스틱 회귀보다 해석이 덜 직관적입니다.</p>`,
  applications: `<p>경제학의 이산선택모형(소비자의 구매 여부 결정 등)에 전통적으로 사용되며, Python에서는 scikit-learn이 아닌 statsmodels의 <code>Probit</code> 클래스로 적합하는 것이 일반적입니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},

/* ========================================================= */
/* [2.2.2] 분류 — 통계·확률 기반 (3) */
/* ========================================================= */
{
  id: 'bayesian-network-classification',
  category: 'sup',
  subcategory: 'classification',
  title: 'Bayesian Network Classification : 베이즈 네트워크 분류',
  subtitle: '변수 간 조건부 의존관계를 방향성 비순환 그래프로 표현해 결합확률로 클래스를 추론하는 확률적 분류 모형',
  overview: `<p>나이브 베이즈가 모든 특성이 클래스 조건부로 서로 독립이라고 가정하는 것과 달리, 베이즈 네트워크는 변수 간 실제 의존관계를 방향성 비순환 그래프(DAG)의 간선으로 표현하고 각 노드에 조건부확률표를 부여합니다. 그래프 구조를 통해 결합확률을 인수분해해 클래스의 사후확률을 계산합니다.</p>`,
  formula: `P(X&#8321;,&#8943;,X&#8344;,Y) = P(Y)&#8290;&#8719;&#8290;&#7522; P(X&#7522;|Parents(X&#7522;))`,
  features: `<p><strong>장점</strong> — 변수 간 실제 의존구조를 반영해 나이브 베이즈보다 현실적인 확률모형을 만들 수 있고 그래프로 관계를 시각화할 수 있습니다.</p><p><strong>단점</strong> — 그래프 구조 학습이 NP-hard에 가까운 어려운 문제이고 변수·간선이 많아지면 조건부확률표 추정에 필요한 데이터가 급증합니다.</p>`,
  applications: `<p>의료 진단 지원 시스템, 고장 진단처럼 변수 간 인과·의존 구조를 함께 설명해야 하는 분야에서 사용되며, Python <code>pgmpy</code> 라이브러리로 구조 학습과 추론을 수행합니다. scikit-learn에는 포함되어 있지 않습니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'gmm-em-classification',
  category: 'sup',
  subcategory: 'classification',
  title: 'GMM(Gaussian Mixture Model) + EM(Expectation-Maximization) Classification : 혼합모형 기반 분류',
  subtitle: '각 클래스의 데이터 분포를 가우시안 혼합모형으로 추정한 뒤 베이즈 규칙으로 사후확률을 계산하는 생성적 분류',
  overview: `<p>클래스별로 특성의 분포를 하나 이상의 가우시안 성분 혼합으로 EM 알고리즘을 통해 추정한 뒤, 새 데이터가 각 클래스 분포에서 나왔을 우도와 사전확률을 베이즈 규칙으로 결합해 사후확률이 가장 높은 클래스로 분류하는 생성적(generative) 접근입니다.</p>`,
  formula: `P(y=k|x) &#8733; P(y=k)&#8290;&#8721;&#8290;&#7580; &#960;&#7580;N(x|&#956;&#8342;&#7580;,&#931;&#8342;&#7580;) &nbsp;(클래스 k의 가우시안 혼합 우도)`,
  features: `<p><strong>장점</strong> — 각 클래스의 분포 형태를 유연하게 다봉(multi-modal) 형태로 표현할 수 있고 새 샘플 생성도 가능한 생성모형입니다.</p><p><strong>단점</strong> — 혼합 성분 수를 정해야 하고 EM이 지역해에 수렴할 수 있어 초기화에 민감합니다.</p>`,
  applications: `<p>클래스 내부에 여러 하위 유형이 존재하는 화자 인식·이상 패턴 분류 등에 사용되며, scikit-learn의 <code>GaussianMixture</code>를 클래스별로 적합한 뒤 사후확률을 비교하는 방식으로 구현합니다.</p>`,
  sklearnFunction: 'GaussianMixture (클래스별 적합)',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/mixture.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.mixture.GaussianMixture.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'naive-bayes-classification',
  category: 'sup',
  subcategory: 'classification',
  title: 'Naive Bayes Classification : 나이브 베이즈 분류',
  subtitle: '모든 특성이 클래스가 주어졌을 때 서로 조건부 독립이라고 단순화(나이브) 가정하는 베이즈 확률 분류기',
  overview: `<p>베이즈 정리로 클래스의 사후확률을 계산하되, 특성 간 결합우도 계산을 단순화하기 위해 모든 특성이 클래스 조건부로 독립이라고 가정합니다. 이 강한 단순화에도 불구하고 텍스트 분류 등에서 실용적으로 좋은 성능을 보여 널리 쓰입니다.</p>`,
  formula: `P(y|x&#8321;,&#8943;,x&#8344;) &#8733; P(y)&#8290;&#8719;&#8290;&#7522; P(x&#7522;|y)`,
  features: `<p><strong>장점</strong> — 학습·예측이 매우 빠르고 적은 데이터로도 안정적으로 동작하며 구현이 단순합니다.</p><p><strong>단점</strong> — 특성 독립 가정이 실제로는 자주 위배되어 특성 간 상관이 강한 데이터에서는 확률 추정이 부정확할 수 있습니다.</p>`,
  applications: `<p>스팸 메일 필터링, 감성분석 등 텍스트 분류의 전통적 베이스라인으로 scikit-learn의 <code>GaussianNB</code>·<code>MultinomialNB</code>·<code>BernoulliNB</code>·<code>ComplementNB</code>가 대표 구현체입니다.</p>`,
  sklearnFunction: 'GaussianNB / MultinomialNB / BernoulliNB / ComplementNB',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/naive_bayes.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},

/* ========================================================= */
/* [2.2.3] 분류 — 거리 기반 (2) */
/* ========================================================= */
{
  id: 'mahalanobis-distance-classification',
  category: 'sup',
  subcategory: 'classification',
  title: 'Mahalanobis Distance Classification : 마할라노비스 거리 분류',
  subtitle: '변수 간 상관과 스케일을 반영한 마할라노비스 거리로 각 클래스 중심까지의 거리를 비교해 분류하는 기법',
  overview: `<p>유클리드 거리가 모든 변수를 동일한 스케일·독립으로 취급하는 것과 달리, 마할라노비스 거리는 클래스별 공분산 행렬의 역행렬을 이용해 변수 간 상관과 척도 차이를 보정한 거리를 계산합니다. 새 관측치를 공분산 구조까지 고려해 가장 가까운 클래스로 분류합니다.</p>`,
  formula: `D&#178;(x,&#956;&#8342;) = (x&#8722;&#956;&#8342;)&#7488;&#931;&#8342;&#8331;&#185;(x&#8722;&#956;&#8342;) &nbsp;(&#931;&#8342;: 클래스 k의 공분산 행렬)`,
  features: `<p><strong>장점</strong> — 변수 간 상관과 스케일 차이를 반영해 유클리드 거리보다 통계적으로 타당한 유사도를 제공합니다.</p><p><strong>단점</strong> — 클래스별 공분산 행렬을 안정적으로 추정하려면 표본 수가 변수 수보다 충분히 많아야 합니다.</p>`,
  applications: `<p>공정 이상 감지, 다변량 이상치 기반 분류 등에 사용되며 scikit-learn의 <code>EmpiricalCovariance</code>/<code>MinCovDet</code>의 <code>mahalanobis()</code> 메서드로 거리를 계산해 임계값 기반 분류에 활용합니다.</p>`,
  sklearnFunction: 'EmpiricalCovariance.mahalanobis()',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/covariance.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.covariance.EmpiricalCovariance.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/covariance/plot_mahalanobis_distances.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'nearest-centroid-classification',
  category: 'sup',
  subcategory: 'classification',
  title: 'Nearest Centroid Classification : 최근접 중심 분류',
  subtitle: '각 클래스의 평균(중심)을 대표점으로 두고 가장 가까운 중심의 클래스로 분류하는 단순 거리 기반 분류기',
  overview: `<p>훈련 단계에서 클래스별 특성 평균(centroid)만 계산해 저장하고, 예측 시에는 새 데이터와 각 클래스 중심 사이의 거리를 비교해 가장 가까운 클래스를 할당합니다. K-최근접이웃과 달리 훈련 샘플 전체가 아닌 클래스당 대표점 하나만 사용합니다.</p>`,
  formula: `&#375;&#8342; = mean(x&#7522; : y&#7522;=k),&nbsp;&nbsp; y&#770; = argmin&#8342; ||x&#8722;&#375;&#8342;||`,
  features: `<p><strong>장점</strong> — 튜닝할 하이퍼파라미터가 없고 학습·예측이 매우 빠르며 단순한 베이스라인으로 적합합니다.</p><p><strong>단점</strong> — 클래스 내부 분산이나 형태가 서로 다르면(비구형 분포) 성능이 크게 떨어집니다.</p>`,
  applications: `<p>고차원 유전자 발현 데이터 분류(수축 중심 분류, shrunken centroid)의 베이스라인으로 자주 쓰이며 scikit-learn의 <code>NearestCentroid</code>로 바로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'NearestCentroid',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/neighbors.html#nearest-centroid-classifier',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.NearestCentroid.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/neighbors/plot_nearest_centroid.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},

/* ========================================================= */
/* [2.3.1] 회귀+분류 — 판별 분석 (2) */
/* ========================================================= */
{
  id: 'linear-discriminant-analysis',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'LDA(Linear Discriminant Analysis) : 선형 판별 분석',
  subtitle: '클래스 간 분산 대비 클래스 내 분산의 비를 최대화하는 방향으로 데이터를 투영해 분류·차원축소를 수행하는 기법',
  overview: `<p>모든 클래스가 동일한 공분산 행렬을 갖는 가우시안 분포를 따른다고 가정하고, 클래스 간 분산과 클래스 내 분산의 비율을 최대화하는 선형 판별축을 찾습니다. 이 축에 데이터를 투영하면 분류 경계는 선형이 되며 동시에 지도 차원축소(최대 K&#8722;1차원)로도 활용됩니다.</p>`,
  formula: `J(w) = w&#7488;S&#8305;w / w&#7488;S&#8367;w &nbsp;(S&#8305;: 클래스 간 산포행렬, S&#8367;: 클래스 내 산포행렬)`,
  features: `<p><strong>장점</strong> — 파라미터가 적고 닫힌 형태 해가 존재해 학습이 빠르며 분류와 차원축소를 동시에 수행할 수 있습니다.</p><p><strong>단점</strong> — 모든 클래스가 같은 공분산을 갖는다는 가정이 깨지면 성능이 저하되고 선형 경계만 표현 가능합니다.</p>`,
  applications: `<p>얼굴 인식(Fisherfaces), 신용등급 분류 등에 사용되며 scikit-learn의 <code>LinearDiscriminantAnalysis</code>로 분류·차원축소 양쪽에 바로 적용할 수 있습니다.</p>`,
  sklearnFunction: 'LinearDiscriminantAnalysis',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/lda_qda.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.discriminant_analysis.LinearDiscriminantAnalysis.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/decomposition/plot_pca_vs_lda.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'quadratic-discriminant-analysis',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'QDA(Quadratic Discriminant Analysis) : 이차 판별 분석',
  subtitle: '클래스마다 서로 다른 공분산 행렬을 허용해 곡선(이차) 형태의 분류 경계를 표현하는 판별 분석',
  overview: `<p>LDA와 달리 클래스별로 별도의 공분산 행렬을 추정해, 클래스마다 분포의 모양(퍼짐 정도·방향)이 다를 수 있음을 반영합니다. 그 결과 판별함수가 입력에 대해 이차식이 되어 곡선 형태의 분류 경계를 표현할 수 있습니다.</p>`,
  formula: `&#948;&#8342;(x) = &#8722;&#189;log|&#931;&#8342;| &#8722; &#189;(x&#8722;&#956;&#8342;)&#7488;&#931;&#8342;&#8331;&#185;(x&#8722;&#956;&#8342;) + log&#960;&#8342;`,
  features: `<p><strong>장점</strong> — 클래스별로 다른 분산 구조를 반영해 LDA보다 유연한 곡선 경계를 표현할 수 있습니다.</p><p><strong>단점</strong> — 클래스마다 별도의 공분산 행렬을 추정해야 해 LDA보다 더 많은 데이터와 파라미터가 필요합니다.</p>`,
  applications: `<p>클래스별 분산 구조가 뚜렷하게 다른 의료 진단·품질관리 분류 문제에 사용되며 scikit-learn의 <code>QuadraticDiscriminantAnalysis</code>로 바로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'QuadraticDiscriminantAnalysis',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/lda_qda.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.discriminant_analysis.QuadraticDiscriminantAnalysis.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/classification/plot_lda_qda.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},

/* ========================================================= */
/* [2.3.2] 회귀+분류 — 트리 및 앙상블 기반 (4, DT·RF는 기존 algorithms.js에 존재해 제외) */
/* ========================================================= */
{
  id: 'catboost',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'CatBoost(Categorical Boosting) : 캣부스트',
  subtitle: '범주형 변수를 자동으로 처리하고 순서형 부스팅으로 예측 목표 누수를 방지하는 그래디언트 부스팅 라이브러리',
  overview: `<p>범주형 변수를 원-핫 인코딩 없이 순서형 타깃 통계(ordered target statistics)로 자동 변환하고, 부스팅 각 단계에서 이전까지의 데이터만 사용하는 순서형 부스팅(ordered boosting)으로 타깃 누수와 과적합을 줄입니다. 대칭 트리(oblivious tree) 구조로 예측 속도도 빠릅니다.</p>`,
  formula: `F&#8340;(x) = F&#8340;&#8331;&#8321;(x) + &#951;&#183;h&#8340;(x) &nbsp;(순서형 부스팅으로 h&#8340; 학습 시 데이터 누수 방지)`,
  features: `<p><strong>장점</strong> — 범주형 변수를 별도 전처리 없이 바로 사용할 수 있고 기본 하이퍼파라미터로도 과적합에 강건합니다.</p><p><strong>단점</strong> — 매우 큰 데이터셋에서는 LightGBM보다 학습 속도가 느릴 수 있습니다.</p>`,
  applications: `<p>범주형 변수 비중이 큰 광고 클릭률 예측, 추천 시스템 랭킹 등에 널리 쓰이며, scikit-learn이 아닌 자체 라이브러리인 <code>catboost</code>의 <code>CatBoostClassifier</code>/<code>CatBoostRegressor</code>(공식 문서 catboost.ai/docs)로 사용합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'gradient-boosting-machine',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'GBM(Gradient Boosting Machine) : 그래디언트 부스팅',
  subtitle: '이전 모델의 잔차(그래디언트)를 다음 약한 학습기가 순차적으로 학습해 결합하는 부스팅 앙상블',
  overview: `<p>매 단계마다 현재까지의 예측과 실제값의 차이(손실함수의 음의 그래디언트)를 다음 약한 학습기(주로 얕은 결정트리)가 학습하도록 하여, 이를 이전 예측에 더해가며 점진적으로 오차를 줄입니다. 배깅과 달리 트리들이 독립적이지 않고 순차적으로 이전 오차를 보정합니다.</p>`,
  formula: `F&#8340;(x) = F&#8340;&#8331;&#8321;(x) + &#951;&#183;h&#8340;(x), &nbsp; h&#8340; &#8776; argmin&#8462; &#8721;&#8290;&#7522;[&#8722;&#8706;L(y&#7522;,F&#8340;&#8331;&#8321;(x&#7522;))/&#8706;F]&#8722;h(x&#7522;)`,
  features: `<p><strong>장점</strong> — 단일 트리보다 예측 정확도가 크게 높고 다양한 손실함수(회귀·분류·순위)에 유연하게 적용됩니다.</p><p><strong>단점</strong> — 트리를 순차적으로 학습해 배깅 계열보다 병렬화가 어렵고 학습률·트리 수 등 튜닝이 까다로우며 과적합 위험이 있습니다.</p>`,
  applications: `<p>정형(테이블) 데이터 경진대회와 실무 예측 모델의 표준 기법으로 scikit-learn의 <code>GradientBoostingClassifier</code>/<code>GradientBoostingRegressor</code>와 더 빠른 <code>HistGradientBoostingClassifier</code>/<code>Regressor</code>가 대표 구현체입니다.</p>`,
  sklearnFunction: 'GradientBoostingClassifier / GradientBoostingRegressor',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/ensemble.html#gradient-boosting',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/ensemble/plot_gradient_boosting_regression.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'lightgbm',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'LightGBM(Light Gradient Boosting Machine) : 라이트 그래디언트 부스팅 머신',
  subtitle: '리프 중심 트리 성장과 히스토그램 기반 분할로 대용량 데이터에서도 빠르게 학습하는 그래디언트 부스팅 라이브러리',
  overview: `<p>레벨 단위로 트리를 키우는 전통적 방식 대신 손실 감소가 가장 큰 리프를 우선 분할하는 리프 중심(leaf-wise) 성장 전략을 사용하고, 연속값을 히스토그램 구간으로 묶어 분할 탐색을 가속합니다. GOSS(그래디언트 기반 샘플링)와 EFB(배타적 특성 묶음)로 대용량·고차원 데이터에서도 메모리·속도 효율을 높였습니다.</p>`,
  formula: `F&#8340;(x) = F&#8340;&#8331;&#8321;(x) + &#951;&#183;h&#8340;(x) &nbsp;(리프 중심 성장 + 히스토그램 기반 분할 탐색으로 h&#8340; 고속 학습)`,
  features: `<p><strong>장점</strong> — 매우 큰 데이터셋에서도 학습 속도와 메모리 효율이 뛰어나고 범주형 변수를 기본 지원합니다.</p><p><strong>단점</strong> — 리프 중심 성장 특성상 데이터가 적을 때는 과적합되기 쉬워 트리 깊이·리프 수 제한이 필요합니다.</p>`,
  applications: `<p>대규모 정형 데이터의 클릭률 예측, 랭킹, 금융 리스크 모델링 등에 널리 쓰이며 scikit-learn이 아닌 자체 라이브러리인 <code>lightgbm</code>(공식 문서 lightgbm.readthedocs.io)의 <code>LGBMClassifier</code>/<code>LGBMRegressor</code>로 사용합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'xgboost',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'XGBoost(Extreme Gradient Boosting) : 익스트림 그래디언트 부스팅',
  subtitle: '2차 도함수 근사와 정규화 항을 결합하고 병렬·분산 처리로 그래디언트 부스팅을 고속화·고도화한 라이브러리',
  overview: `<p>손실함수를 1차뿐 아니라 2차 테일러 근사까지 활용해 각 트리의 최적 분할과 리프 값을 더 정교하게 계산하고, 트리 복잡도에 대한 L1/L2 정규화 항을 목적함수에 명시적으로 포함해 과적합을 억제합니다. 히스토그램 기반 분할, 결측치 자동 처리, 병렬·분산·GPU 학습을 지원합니다.</p>`,
  formula: `Obj = &#8721;&#8290;&#7522; L(y&#7522;,&#375;&#7522;) + &#8721;&#8290;&#7532; &#937;(f&#7532;) &nbsp;(&#937;(f)=&#947;T+&#189;&#955;||w||&#178;, T: 리프 수, w: 리프 가중치)`,
  features: `<p><strong>장점</strong> — 정규화 항 덕분에 과적합에 강건하고 결측치를 자동으로 처리하며 분산·GPU 학습으로 대규모 데이터에도 확장됩니다.</p><p><strong>단점</strong> — 하이퍼파라미터 수가 많아 튜닝 부담이 크고 LightGBM 대비 기본 설정에서는 학습 속도가 느릴 수 있습니다.</p>`,
  applications: `<p>Kaggle 등 정형 데이터 경진대회에서 가장 많이 쓰이는 모델 중 하나이며, scikit-learn이 아닌 자체 라이브러리인 <code>xgboost</code>(공식 문서 xgboost.readthedocs.io)의 <code>XGBClassifier</code>/<code>XGBRegressor</code>(scikit-learn 호환 API 제공)로 사용합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},

/* ========================================================= */
/* [2.3.3] 회귀+분류 — 거리 기반 (2) */
/* ========================================================= */
{
  id: 'k-nearest-neighbors',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'K-NN(k-Nearest Neighbors) : k-최근접 이웃',
  subtitle: '새 데이터와 가장 가까운 k개의 훈련 샘플을 찾아 다수결(분류) 또는 평균(회귀)으로 예측하는 인스턴스 기반 학습',
  overview: `<p>별도의 모델 파라미터를 학습하지 않고 훈련 데이터를 그대로 저장해 두었다가, 예측 시점에 새 데이터와 가장 가까운 k개 이웃을 찾아 분류에서는 다수결 클래스를, 회귀에서는 이웃값의 평균을 예측값으로 사용하는 게으른 학습(lazy learning) 방식입니다.</p>`,
  formula: `y&#770; = mode{y&#7522; : x&#7522; &#8712; N&#8342;(x)} (분류), &nbsp; y&#770; = (1/k)&#8721;&#8290;&#7522;&#8712;N&#8342;(x) y&#7522; (회귀)`,
  features: `<p><strong>장점</strong> — 알고리즘이 단순하고 학습 단계가 없으며 결정경계 형태에 대한 가정이 없어 유연합니다.</p><p><strong>단점</strong> — 예측 시마다 전체(또는 인덱싱된) 훈련 데이터와 거리를 계산해야 해 데이터가 클수록 느려지고 고차원에서는 거리 개념이 무의미해지는 차원의 저주에 취약합니다.</p>`,
  applications: `<p>추천 시스템의 협업 필터링, 이미지 유사도 검색 등에 사용되며 scikit-learn의 <code>KNeighborsClassifier</code>/<code>KNeighborsRegressor</code>로 바로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'KNeighborsClassifier / KNeighborsRegressor',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/neighbors.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/neighbors/plot_classification.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'support-vector-machine',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'SVM(Support Vector Machine) : 서포트 벡터 머신',
  subtitle: '클래스 사이의 마진(여백)을 최대화하는 결정경계를 찾아 분류·회귀를 수행하는 커널 기반 모델',
  overview: `<p>두 클래스를 나누는 여러 초평면 중 가장 가까운 데이터(서포트 벡터)까지의 거리(마진)가 최대가 되는 초평면을 찾습니다. 커널 트릭을 적용하면 원본 공간에서는 선형으로 분리되지 않는 데이터도 고차원 특성 공간에서 분리할 수 있으며, 회귀에서는 ε-불감대(epsilon-insensitive) 손실을 사용하는 SVR로 확장됩니다.</p>`,
  formula: `min &#189;||w||&#178; + C&#8721;&#8290;&#7522;&#958;&#7522; &nbsp; s.t. y&#7522;(w&#7488;x&#7522;+b) &#8805; 1&#8722;&#958;&#7522; &nbsp;(&#958;&#7522;: 여유변수, C: 규제 강도)`,
  features: `<p><strong>장점</strong> — 고차원 특성 공간에서도 마진 최대화로 일반화 성능이 우수하고 커널로 비선형 경계를 유연하게 표현합니다.</p><p><strong>단점</strong> — 훈련 데이터가 많아지면 커널 행렬 계산 비용이 급격히 커지고 커널·규제 파라미터 튜닝이 까다롭습니다.</p>`,
  applications: `<p>텍스트 분류, 이미지 분류, 생물정보학의 유전자 발현 분류 등에 널리 쓰이며 scikit-learn의 <code>SVC</code>/<code>SVR</code>·선형 전용의 <code>LinearSVC</code>/<code>LinearSVR</code>이 대표 구현체입니다.</p>`,
  sklearnFunction: 'SVC / SVR',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/svm.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/svm/plot_svm_kernels.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},

/* ========================================================= */
/* [2.3.4] 회귀+분류 — 차원 축소 + 예측 (4) */
/* ========================================================= */
{
  id: 'principal-component-regression',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'PCR(Principal Component Regression) : 주성분 회귀',
  subtitle: 'PCA로 추출한 주성분을 설명변수로 사용해 다중공선성을 우회하며 회귀를 수행하는 2단계 기법',
  overview: `<p>1단계로 설명변수에 PCA를 적용해 서로 직교하는 주성분(분산이 큰 순서로 정렬)을 추출하고, 2단계로 이 주성분 일부를 설명변수 삼아 최소제곱 회귀를 적합합니다. 주성분은 반응변수 y를 보지 않고(비지도) 추출된다는 점이 PLS와의 핵심 차이입니다.</p>`,
  formula: `X &#8776; TP&#7488; &nbsp;(T: 주성분 점수), &nbsp; y&#770; = T&#946;&#775;`,
  features: `<p><strong>장점</strong> — 다중공선성이 심한 변수들을 소수의 직교 주성분으로 요약해 안정적인 회귀계수를 얻습니다.</p><p><strong>단점</strong> — 주성분이 반응변수와 무관하게(분산 기준만으로) 추출되어, 분산은 작지만 y 예측에 중요한 성분이 버려질 위험이 있습니다.</p>`,
  applications: `<p>분광분석 등 변수 수가 많고 상관이 극심한 화학계량학 데이터 회귀에 사용되며, scikit-learn의 <code>PCA</code>와 <code>LinearRegression</code>을 파이프라인으로 연결해 구현합니다.</p>`,
  sklearnFunction: 'PCA + LinearRegression',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/decomposition.html#pca',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/cross_decomposition/plot_pcr_vs_pls.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'partial-least-squares-regression',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'PLS(Partial Least Squares) : 부분 최소제곱 회귀',
  subtitle: '설명변수와 반응변수의 공분산을 최대화하는 잠재성분을 동시에 추출해 회귀를 수행하는 지도 차원축소 회귀',
  overview: `<p>PCR이 설명변수의 분산만 보고 성분을 추출하는 것과 달리, PLS는 설명변수와 반응변수 사이의 공분산이 최대가 되는 방향으로 잠재성분을 추출합니다. 따라서 소수의 성분만으로도 반응변수 예측에 실제로 도움이 되는 정보를 효율적으로 포착합니다.</p>`,
  formula: `X = TP&#7488;+E,&nbsp; y = TQ&#7488;+F &nbsp;(T: X·y의 공분산을 최대화하도록 추출된 잠재성분)`,
  features: `<p><strong>장점</strong> — 변수 수가 표본 수보다 많고(p&gt;n) 다중공선성이 극심한 데이터에서도 안정적으로 적합하며 PCR보다 적은 성분으로 좋은 예측력을 얻습니다.</p><p><strong>단점</strong> — 잠재성분 수를 교차검증으로 정해야 하고 개별 원변수의 기여도 해석이 PCR보다 복잡합니다.</p>`,
  applications: `<p>근적외선(NIR) 분광 데이터로 성분 함량을 예측하는 화학계량학의 표준 기법이며 scikit-learn의 <code>PLSRegression</code>으로 바로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'PLSRegression',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/cross_decomposition.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.cross_decomposition.PLSRegression.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/cross_decomposition/plot_compare_cross_decomposition.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'pls-discriminant-analysis',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'PLS-DA(Partial Least Squares Discriminant Analysis) : 부분 최소제곱 판별 분석',
  subtitle: '클래스 라벨을 더미변수로 변환해 PLS 회귀를 분류 문제에 적용하는 지도 차원축소 판별 기법',
  overview: `<p>범주형 클래스 라벨을 원-핫(더미) 형태의 수치 반응변수로 바꾼 뒤 PLS 회귀를 적용하고, 예측된 연속값을 다시 클래스로 변환(가장 큰 값의 클래스 선택)하는 방식입니다. 변수 수가 매우 많고 표본이 적은 데이터에서 LDA보다 안정적으로 작동합니다.</p>`,
  formula: `Y&#8290;&#8340;&#8358;&#8350;&#8358;&#8351; = TQ&#7488; &nbsp;(Y: 클래스의 더미 인코딩 행렬), &nbsp; y&#770; = argmax&#8342; &#375;&#8342;`,
  features: `<p><strong>장점</strong> — 변수 수가 표본 수보다 많은 고차원 데이터에서도 안정적으로 분류 경계를 학습하고 변수 중요도(VIP 점수)를 함께 제공합니다.</p><p><strong>단점</strong> — 클래스가 불균형하거나 3개 이상일 때 더미 인코딩 방식에 따라 결과가 민감해질 수 있습니다.</p>`,
  applications: `<p>대사체·유전체 데이터 기반 질병군 분류, 식품 원산지 판별 등 변수가 표본보다 많은 생물정보학 분류에 널리 쓰이며, scikit-learn의 <code>PLSRegression</code>에 더미 인코딩된 클래스 라벨을 반응변수로 입력해 구현합니다.</p>`,
  sklearnFunction: 'PLSRegression (더미 인코딩 클래스 라벨 사용)',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/cross_decomposition.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.cross_decomposition.PLSRegression.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'supervised-pca',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'Supervised PCA(Supervised Principal Component Analysis) : 감독 주성분 분석',
  subtitle: '반응변수와 유의하게 연관된 변수만 선별한 뒤 PCA를 적용해 예측에 유용한 주성분을 얻는 지도 차원축소',
  overview: `<p>표준 PCA가 반응변수를 전혀 참고하지 않고 분산이 큰 방향을 찾는 것과 달리, 감독 PCA는 먼저 반응변수와의 단순 상관·회귀계수가 유의한 변수만 골라낸 뒤, 그 부분집합에 대해서만 PCA를 적용해 주성분을 추출합니다. 이렇게 하면 추출된 성분이 예측에 실제로 기여할 가능성이 높아집니다.</p>`,
  formula: `X&#8290;&#8340;&#8358;&#8324; = {x&#8290;&#7522; : |corr(x&#8290;&#7522;,y)| &gt; &#952;} &#8594; PCA(X&#8290;&#8340;&#8358;&#8324;) &#8594; 회귀/분류`,
  features: `<p><strong>장점</strong> — 반응변수와 무관한 잡음 변수를 사전에 제거해 표준 PCA보다 예측에 유용한 성분을 얻을 가능성이 높습니다.</p><p><strong>단점</strong> — 변수 선택 임계값 &#952;을 정해야 하고, 선택 단계와 성분 추출 단계가 분리되어 있어 완전한 end-to-end 최적화는 아닙니다.</p>`,
  applications: `<p>수천~수만 개의 유전자 발현값에서 생존시간·질병 여부와 관련된 유전자만 추려 위험 점수를 예측하는 유전체 연구에서 제안된 기법(superpc)이며, scikit-learn에는 전용 클래스가 없어 <code>SelectKBest</code> 등으로 변수를 먼저 거른 뒤 <code>PCA</code>를 적용하는 방식으로 구현합니다.</p>`,
  sklearnFunction: 'SelectKBest + PCA (파이프라인으로 근사 구현)',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/feature_selection.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},

/* ========================================================= */
/* [2.3.5] 회귀+분류 — 신경망 기반 (5, CNN/RNN은 List3.md에서 한 항목이나 별도 항목으로 분리 작성) */
/* ========================================================= */
{
  id: 'autoencoder-supervised',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'AE(Autoencoder) : 오토인코더',
  subtitle: '입력을 저차원 잠재코드로 압축(인코더)한 뒤 원래대로 복원(디코더)하도록 학습해 표현을 학습하는 신경망',
  overview: `<p>인코더가 입력을 저차원 잠재벡터로 압축하고 디코더가 이 잠재벡터로부터 원래 입력을 최대한 복원하도록 재구성 오차를 최소화하며 학습합니다. 비지도로 학습된 잠재표현(또는 재구성 오차 자체)을 지도학습의 특성 추출·전처리·이상치 점수로 활용할 수 있어 지도학습 파이프라인에 편입되기도 합니다.</p>`,
  formula: `z = f&#8290;&#8340;&#8331;&#8330;&#8290;&#8354;&#8330;&#7522;(x),&nbsp; x&#770; = f&#8290;&#8333;&#8330;&#8330;&#8290;&#8354;&#8330;&#7522;(z),&nbsp; L = ||x&#8722;x&#770;||&#178;`,
  features: `<p><strong>장점</strong> — 라벨 없이 데이터의 저차원 표현을 학습할 수 있고 이 표현을 이후 지도학습 모델의 입력 특성으로 재사용할 수 있습니다.</p><p><strong>단점</strong> — 재구성 성능이 좋다고 해서 다운스트림 예측 과제에 항상 유용한 표현이 학습되는 것은 아니며 잠재차원·구조 설계에 실험이 필요합니다.</p>`,
  applications: `<p>고차원 센서·이미지 데이터를 저차원으로 압축해 회귀·분류 모델의 입력 특성으로 사용하거나, 정상 데이터 재구성 오차를 이상탐지 점수로 활용하는 데 쓰이며, PyTorch·TensorFlow/Keras로 직접 구현하는 것이 일반적입니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'convolutional-neural-network',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'CNN(Convolutional Neural Network) : 합성곱 신경망',
  subtitle: '지역적 수용영역과 가중치 공유를 갖는 합성곱 필터로 이미지 등 격자 구조 데이터의 특징을 계층적으로 추출하는 신경망',
  overview: `<p>작은 크기의 합성곱 필터가 입력의 국소 영역을 슬라이딩하며 특징맵을 생성하고, 여러 층을 거치며 저수준(경계·질감)에서 고수준(형태·객체) 특징으로 점차 추상화됩니다. 필터 가중치를 전체 위치에서 공유해 완전연결 신경망보다 훨씬 적은 파라미터로 이미지의 평행이동 불변성을 자연스럽게 학습합니다.</p>`,
  formula: `(f * x)(i,j) = &#8721;&#8290;&#8350;,&#8353; f(m,n)&#183;x(i&#8722;m,j&#8722;n) &nbsp;(합성곱 연산)`,
  features: `<p><strong>장점</strong> — 가중치 공유로 완전연결 신경망보다 파라미터가 훨씬 적고 이미지의 지역적 패턴과 평행이동 불변성을 효율적으로 포착합니다.</p><p><strong>단점</strong> — 대규모 라벨 데이터와 GPU 연산이 필요하고 회전·스케일 변화에는 별도의 데이터 증강 없이는 취약합니다.</p>`,
  applications: `<p>이미지 분류·객체 탐지·의료영상 판독의 표준 아키텍처로 ResNet·EfficientNet 등이 대표적이며, Hugging Face의 <code>microsoft/resnet-50</code> 같은 사전학습 모델을 <code>transformers</code> 라이브러리로 바로 활용할 수 있습니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: 'https://huggingface.co/microsoft/resnet-50',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'recurrent-neural-network',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'RNN(Recurrent Neural Network) : 순환 신경망',
  subtitle: '이전 시점의 은닉상태를 현재 입력과 함께 반영해 순차 데이터의 시간적 의존성을 학습하는 신경망',
  overview: `<p>매 시점마다 은닉상태를 갱신하면서 이전 시점의 정보를 다음 시점으로 전달해, 가변 길이의 순차 데이터(시계열·텍스트) 안의 시간적 의존관계를 학습합니다. 장기 의존성 문제를 완화한 LSTM·GRU가 실무에서 주로 쓰이는 변형입니다.</p>`,
  formula: `h&#8340; = tanh(W&#8462;&#8462;h&#8340;&#8331;&#8321; + W&#8348;&#8462;x&#8340; + b) &nbsp;(h&#8340;: 시점 t의 은닉상태)`,
  features: `<p><strong>장점</strong> — 가변 길이의 순차 데이터를 자연스럽게 다루고 시간적 순서 정보를 명시적으로 반영합니다.</p><p><strong>단점</strong> — 시점마다 순차적으로 계산해야 해 병렬화가 어렵고 긴 시퀀스에서는 그래디언트 소실·폭발 문제가 발생하기 쉬워 최근에는 Transformer로 대체되는 추세입니다.</p>`,
  applications: `<p>음성 인식, 시계열 예측, 기계번역의 초기 표준 모델로 사용되었으며, RNN과 Transformer의 장점을 결합한 RWKV 같은 최신 구조가 Hugging Face 생태계에 통합되어 소개되고 있습니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: 'https://huggingface.co/blog/rwkv',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'multilayer-perceptron',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'MLP(Multilayer Perceptron) : 다층 퍼셉트론',
  subtitle: '여러 층의 완전연결(fully-connected) 뉴런과 비선형 활성화함수로 구성된 가장 기본적인 순방향 신경망',
  overview: `<p>입력층·하나 이상의 은닉층·출력층이 모두 완전히 연결된 구조로, 각 은닉층은 이전 층의 출력에 가중합을 구한 뒤 비선형 활성화함수(ReLU 등)를 적용합니다. 은닉층이 충분히 있으면 보편근사정리에 의해 임의의 연속함수를 근사할 수 있어 회귀·분류 모두에 사용됩니다.</p>`,
  formula: `h&#8317;&#8318;&#8317; = &#963;(W&#8317;&#8318;&#8317;h&#8317;&#8318;&#8331;&#8321;&#8317; + b&#8317;&#8318;&#8317;) &nbsp;(&#963;: 비선형 활성화함수)`,
  features: `<p><strong>장점</strong> — 구조가 단순하면서도 표현력이 높아 다양한 정형 데이터의 비선형 회귀·분류에 두루 활용됩니다.</p><p><strong>단점</strong> — 이미지·순차 데이터의 공간적·시간적 구조는 반영하지 못해 CNN·RNN·Transformer보다 해당 도메인에서 비효율적입니다.</p>`,
  applications: `<p>정형(표) 데이터의 회귀·분류, 다른 신경망 아키텍처의 최종 출력층 구성요소 등으로 광범위하게 쓰이며 scikit-learn의 <code>MLPClassifier</code>/<code>MLPRegressor</code>로 바로 적합할 수 있습니다.</p>`,
  sklearnFunction: 'MLPClassifier / MLPRegressor',
  sklearnGuideURL: 'https://scikit-learn.org/stable/modules/neural_networks_supervised.html',
  sklearnAPIURL: 'https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html',
  sklearnExampleURL: 'https://scikit-learn.org/stable/auto_examples/neural_networks/plot_mlp_training_curves.html',
  huggingfaceURL: '',
  spaceURL: '',
  papersWithCodeURL: ''
},
{
  id: 'transformer',
  category: 'sup',
  subcategory: 'reg-class',
  title: 'Transformer : 트랜스포머',
  subtitle: '순환 구조 없이 셀프 어텐션만으로 시퀀스 내 모든 위치 간 의존관계를 병렬적으로 학습하는 신경망 아키텍처',
  overview: `<p>순차적으로 은닉상태를 전달하는 RNN과 달리, 셀프 어텐션(self-attention) 메커니즘으로 시퀀스의 모든 위치 쌍 사이의 연관도를 한 번에 계산해 병렬 학습이 가능합니다. 위치 인코딩으로 순서 정보를 보완하고, 인코더-디코더 또는 인코더/디코더 단독 구조로 다양한 과제에 적용됩니다.</p>`,
  formula: `Attention(Q,K,V) = softmax(QK&#7488;/&#8730;d&#8342;)&#183;V`,
  features: `<p><strong>장점</strong> — 병렬 학습이 가능해 대규모 데이터·모델로 확장하기 쉽고 장거리 의존관계를 RNN보다 잘 포착합니다.</p><p><strong>단점</strong> — 시퀀스 길이의 제곱에 비례하는 어텐션 계산 비용이 크고 대량의 데이터와 연산자원이 필요합니다.</p>`,
  applications: `<p>BERT·GPT 계열의 자연어처리, ViT 계열의 이미지 분류, 시계열 예측(Autoformer 등) 전반의 사실상 표준 아키텍처로 Hugging Face <code>transformers</code> 라이브러리가 방대한 사전학습 모델과 API를 제공합니다.</p>`,
  sklearnFunction: '',
  sklearnGuideURL: '',
  sklearnAPIURL: '',
  sklearnExampleURL: '',
  huggingfaceURL: 'https://huggingface.co/docs/transformers/index',
  spaceURL: '',
  papersWithCodeURL: ''
},
